### ISSUE TITLE
[question] What is the purpose of compile.js?

### ISSUE THREAD

**Issue by 3amprogrammer** [davezuko/react-redux-starter-kit#1008]
As far as I understand it's all job is to wrap webpack with some nice debug info and copy static folder to dist folder, am I right? 

I ask this questions cause it seems meaningless to me, as a newbie, and I really like to understand the tools that I am using. How this, pretty complicated for me, compile wrapper is helpful (besides that it copies static content, which as far as I know webpack can accomplish)?

By the way, why you have called folder with configs build? Until yesterday I tough that dist/build are synonyms and should contain final package.

Thanks for the time and effort you guys have put into creating this starter-kit.

**Comment by davezuko** [comment]
Really sorry for the late reply, but in case you are still interested:

The original intention of `bin/compile` was to just house the programmatic execution of the compilation task. The compiler wrapper, which was used by `bin/compile` was just there as an abstraction over the webpack's `compiler.run` to make it easy to use with any arbitrary webpack config. That is, if you extended the project and needed to perform programmatic builds for other reasons, you could just use that wrapper. I have since decided, to your point, that it is mostly an unnecessary abstraction, and so it has since been removed.

The `build` folder was meant to house all build-related configuration, whereas `config` was meant to be something that the user touched. Meaning, `build` would always remain the same, and in order to influence it, you would edit what was in `config`. Again, I have taken steps to simplify this in hopes of making it more straightforward.

This commit may be of interest to you: https://github.com/davezuko/react-redux-starter-kit/commit/ad5924a72a7805fed916cc010f2970fb730d6520
