### ISSUE TITLE
React-Foundation or React-toolbox w/ RRSK

### ISSUE THREAD

**Issue by MicahRamirez** [davezuko/react-redux-starter-kit#1020]
After looking at the webpack config, it seems though we have the proper logic to be pulling in style resources from node_modules. However when I attempt to use either react-foundation or react-toolbox components none of their styling is being rendered. Is there anything specific I should be doing to get these to work ?

**Comment by o1dnik** [comment]
To check if your default style is being pulled correctly you have to check if you import correct styles in corresponding routes / components. 
I've tried (successfully) with `bootstrap-sass` module laying in `node_modules` folder. I simply added a soft link from the folder I use (which is not necessary actually) and imported sass files into the core, base, components themselves, whatever else. But I didn't use javascript for bootstrap because you either have to rely on monolithic React-Bootstrap or just write your own library of components. Hence, I started building own library with custom style. So far so good. And no maintenance pain with customization of third-party components.

**Comment by apaatsio** [comment]
Here's a config for getting react-toolbox to work with react-redux-starter-kit: https://github.com/apaatsio/react-redux-starter-kit/commit/8d152ee75a10b23132bc8c0796a0752b235bd237

**Comment by davezuko** [comment]
See ^^
