### ISSUE TITLE
How to wait for reducer injection?

### ISSUE THREAD

**Issue by simonedavico** [davezuko/react-redux-starter-kit#1049]
I have a page with a `Parent` tab and two secondary tabs `ChildA` and `ChildB`.
`ChildA` should be the default tab when I select the `Parent` tab; also, the reducer for `Parent` is injected asynchronously.

Now, when entering a child, say `ChildA`, I would like to check some state from the store and dispatch an action in some cases. The problem is that since the state I'm interested in is in a property of the state injected asynchronously in `getComponent` for `parent`, it could still be unavailable in some cases (e.g, when loading `/parent/childA` directly).

Has someone encountered a similar problem? Is there a way to wait for the injection to finish before entering the child route, or should I tackle this with a different approach?

This is my route configuration:

``` javascript
export default (store) => ({
  path: 'parent',
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    console.log('store', store);
    /*  Webpack - use 'require.ensure' to create a split point
     and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
       dependencies for bundling   */
      const Parent = require('./containers/ParentContainer').default;
      const reducer = require('./modules/parent').default;

      //add the reducer to the store on key 'rimborsi'
      injectReducer(store, { key: 'parent', reducer });

      /*  Return getComponent   */
      cb(null, Parent);

      /* Webpack named bundle   */
    }, 'parent')
  },
  indexRoute: {
    onEnter: (nextState, replace) =>
      replace('/parent/childA')
  },
  childRoutes: [
    {
      path: 'childA',
      component: ChildA,
      onEnter: (nextState, replace) => {
         store.getState().parent //this can be undefined at this point!
      }
    },
    {
      path: 'childB',
      component: ChildB
    }
  ]
})
```

**Comment by zentuit** [comment]
@simonedavico : have you solved this? I'm running into the same issue.

**Comment by simonedavico** [comment]
@zentuit in the end I decided to refactor my approach. Switching from `redux-thank` to `redux-saga` helped a lot :)

Nevertheless, it would be interesting to see more concretely how you solved it, if you are willing to share a code sample!

**Comment by zentuit** [comment]
Sure no problem: 
```
export default store => ({
  path: 'collection/:slug',
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    /*  Webpack - use 'require.ensure' to create a split point
        and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
          dependencies for bundling   */
      const Collection = require('./containers/CollectionContainer').default
      const module = require('./modules/collections')
      const reducer = module.default

      /*  Add the reducer to the store on key 'collection'  */
      injectReducer(store, { key: 'collection', reducer })

      module.pageLoad(nextState.params.slug)(store.dispatch)
      /*  Return getComponent   */
      cb(null, Collection)

    /* Webpack named bundle   */
    }, 'collection')
  }
})
```

**Comment by simonedavico** [comment]
I see. Basically you perform your logic when you load the component for the route. I don't see where you access to the store slice you inject (i.e., `collection`) though. That is what I did not manage to achieve :)

**Comment by zentuit** [comment]
If I read this correctly, I don't access any state date here. I simply call a function on the module. That module handles dispatching the proper actions (in my case its dispatching async loading actions). 

I originally had a saga that listened for LOCATION_CHANGE and then put the async loading actions. But in this case, the reducer might load after the saga took the LOCATION_CHANGE so the reducer would not update the state. So sometimes the reducer would load before the async successes, sometimes after - it depended on how fast the async call took.

With this change, I know I can dispatch the async calls because I know that the reducer is loaded and ready.

**Comment by MichaelIT** [comment]
@zentuit I follow your suggestion, and add a function like `module.pageLoad` in your code after `injectReducer ` function.
But, I can not get `action` which dispatch in `module.pageLoad` in reducer every time after refresh web page.
I think it is because of when a `action` dispatch in `module.pageLoad`, `injectReducer` has not completed inject.
