### ISSUE TITLE
Missing tests?

### ISSUE THREAD

**Issue by janoist1** [davezuko/react-redux-starter-kit#1062]
I use this starter kit in a project and I was told by a colleague there should be tests for `AppContainer`, `createStore`, `reducers`. I did not write tests because I guess there must be a reason why the author skipped them...
Now I am unsure, don't they need to be covered too?
Thanks.

**Comment by jonaswindey** [comment]
You're right. Having an error in AppContainer won't make the tests fail, which it should. Feel free to add the test. If not I'll send a PR

**Comment by davezuko** [comment]
The tests that exist are there simply for demonstration purposes after users asked how tests could/should look. I don't really have any intentions on adding more unit tests to this project, primarily due to severe time limitations, but you are right that in a real application there _should_ be more tests. A PR would be welcome, however!
