### ISSUE TITLE
Multiple components per route

### ISSUE THREAD

**Issue by ramikh86** [davezuko/react-redux-starter-kit#1076]
Hi, i noticed that each route exposes one component(or container). What should i do if i want to use multiple components in a route? index.js returns a container which returns one component, should that component include my sub components? isn't that too much?
Thanks

**Comment by bhj** [comment]
Sure, you can use any "view" (e.g. HomeView) to return any number of other components. In React you can return multiple elements/components as long as they are _wrapped_ in a single one.

The "containers" are solely for connecting a view to the store, so that the view components need no knowledge of Redux and receive data from the store passed as normal props. Then you can pass those props down to sub-components as necessary.

**Comment by caseyduquettesc** [comment]
Generally, you would do as @bhj suggested and wrap multiple components. If, however, you feel the "need" to specify multiple components on a route, that is certainly possible. I do it in just one place where I compose different layouts based on the page. `react-router` `Route`'s have a `components` property that you would use in place of `component`. 

Now, the reason I do it is probably not for the same reason you want to do it. You may notice I use **components** and only specify one component. Using `components` has the added benefit of letting you name the the component you pass in. By assigning it a name, we can check if the component was provided later on. Instead of simply rendering/not rendering something, we can render/render something else.

In the code below, we have a set of localized routes (/locale), and within that we have routes that should and should not have a section rendered on the page that contain some frequently asked questions (faq). There was a time when multiple routes would show the faq, but now there is just one. But where we don't want to render the faq, the page looks off, so we want to render something else, a placeholder that's maybe a bit smaller, with no content in it. Of course there's many ways to accomplish this, and I'm not suggesting it's the best, but it works.

Here's an example:

```jsx
<Route path='/' component={MainLayout}>

{/* Localized urls within the app */}
<Route path={i18n.language}>
  <Route components={{ faq: WithFrequentlyAskedQuestions }}>
    <Route component={WithBreadcrumbs}>
      <Route component={WithNavigation}>
        {/* Index page the only one to have faq, but we could move any route here to add faq to that page as well */}
        <IndexRoute component={IndexView} onLeave={onLeaveIndex} />
      </Route>
    </Route>
  </Route>

  <Route component={WithBreadcrumbs}>
    <Route component={WithNavigation}>
      {/* Routes with breadcrumbs, with side navigation, but no faq below the header */}
    </Route>
  </Route>
</Route>

</Route>
```

In my MainLayout.js file:

```jsx
import React, { PropTypes } from 'react'
import Header from 'app/Header'
import Footer from 'app/Footer'

function MainLayout ({ children, faq }) {
  return (
    <div className='page-container'>
      <div className='view-container'>
        {/* Elements present on every page */}
        <Header />
        {/* If there was no faq component passed in, then render a smaller placeholder */}
        {!faq &&
          <div className='no-faqs' />
        }
        {faq}
        {/* Wrap the lower portion of the site */}
        {children}
        <div className='footer-spacer' />
      </div>
      <Footer />
    </div>
  )
}

MainLayout.propTypes = {
  children : PropTypes.element,
  faq      : PropTypes.element
}

export default MainLayout
```

**Comment by ramikh86** [comment]
Thank you all, that explains it. People who are new to this gets confused a little but not anymore and i think im having more understanding of the architectural design of these projects
