### ISSUE TITLE
Is it possible to move any dependencies to devDependencies?

### ISSUE THREAD

**Issue by danielyaa5** [davezuko/react-redux-starter-kit#1085]
I dont understand why there are sass, webpack, and babel related packages in dependencies, couldnt these be moved to devDependencies?

**Comment by davezuko** [comment]
@danielyaa5 they were dev in the past, but because this project is not something that is distributable as a library, and must be built in full time, the concept of dev vs regular dependencies does not really apply. A lot of users were having trouble in CI environments where npm would only install regular dependencies with `NODE_ENV=production`, so we made the decision to make all build-related code a dependency, while keeping dev-only deps in devDeps.

Hope that makes sense. It did used to be the way you are thinking.

**Comment by danielyaa5** [comment]
Totally makes sense, just wondering if those dependencies which normally would be for development get compiled into the build code?

**Comment by davezuko** [comment]
They should not be, at least in production; if you see some that are, please let me know and we can patch it. Certain dev-only packages have actually been removed, such as redux-devtools, in favor of extensions, and others like redbox-react are only included when HMR is enabled, so you should not have to worry about having an artificially inflated prod bundle, despite the devDeps vs deps dilemma.
