### ISSUE TITLE
shouldn't babel be in devdeps?

### ISSUE THREAD

**Issue by mezod** [davezuko/react-redux-starter-kit#109]
Hi, I am trying to properly understand how do the dependencies and devdependencies actually work in the webpack.config and seeing your example I wonder, shouldn't Babel be under the devDependencies? When is Babel used in production? Isn't ES6 already transpiled when creating the dist files?

Additionally, I'd like to ask if someone understands the reasoning behind the changes @gaearon made in his fork https://github.com/gaearon/react-redux-starter-kit/blob/master/package.json ? He has a lot of packages under dependencies that should be in the dev environment, like testing for example.

I understand this is closely related to how deployment is done, I assume you guys generate the dist/ while in development and then tarball it to the server where you untar it? 

PS: Sorry if this doesn't really belong here

**Comment by davezuko** [comment]
Hey, babel is still a dependency in production because it transpiles things like `import` statements back down to CommonJS. Also, it's a bit confusing, but the bundle compiled into `~/dist/server` is not actually the server, it's just some utility methods/exports provided from the React application so that it can be safely rendered on the server.

As far as @gaearon 's fork, that's just how this repo used to look a long time ago when I was still having trouble getting TravisCI to build the application correctly (it wasn't installing devDependencies with the current configuration, which I wrongly "solved" by just moving them to regular dependencies).

Regarding deployment, you need the server source code still, so I generally just push the source code to a dev/test branch, have that run CI checks for compilation and unit tests, and then serve the compiled application (which needs both `dist` and `server`) from there.

Does that make sense?

**Comment by mezod** [comment]
Thanks @davezuko , I guess my confusion appeared because I didn't consider the server-side code of the application also uses Babel.

What you say makes a lot of sense. I'll just try to get more in detail with the deployment. If I understood correctly, you first push your code to a development branch, where you run tests and other checks to finally compile the code. This means that dist/ is generated in the development branch. Then you merge it with production, and pull the production branch from the server (which contains the bundled dist/ code for the client and the server/ code for the api/backend). At this point, npm install --production makes the rest of the work. Is this correct?

**Comment by davezuko** [comment]
That's close, but the branch doesn't actually commit the dist folder or forward it along in any way. [My team follows something similar to Gitflow](https://github.com/GasStationTV/angular-coding-exercise#version-control), which means we deploy to a development branch, which then runs a CI build and the dist files are deployed to our development server (if you only have a production server the dist files would just be discarded). If we are then satisfied and wish to move to production, the master branch will then completely rebuild the project after a successful CI check on the PR.

Essentially, we never pass along the dist files, they're always rebuilt in the target environment. CI checks along the way are just there to make sure the application doesn't have errors and we can be sure that the build will succeed.

**Comment by mezod** [comment]
great thanks for the explanation!
