### ISSUE TITLE
About new error handle

### ISSUE THREAD

**Issue by NE-SmallTown** [davezuko/react-redux-starter-kit#1120]
I notice that current error handle is not friendly because it shows errors in the screen with the **red** background color, and no error in the brower console.

And I find that the official kit [create-react-app](https://github.com/facebookincubator/create-react-app) and someone else i.e. [redux-examples](https://github.com/reactjs/redux/tree/master/examples),their UI of error handle is beautiful in my opinion and show the error in the console too.

This is the shortcut of the UI : [Screenshot](https://github.com/facebookincubator/create-react-app/releases/tag/v0.6.0)

I think they both do this by useing the scripts or dev-util below:

[react-scripts](https://github.com/facebookincubator/create-react-app/tree/7d66ba176a879b3ad43b220c5217b848249daa2e/packages/react-dev-utils) and I think the core file is [webpackHotDevClient.js](https://github.com/facebookincubator/create-react-app/blob/7d66ba176a879b3ad43b220c5217b848249daa2e/packages/react-dev-utils/webpackHotDevClient.js)

So, could you add it or update current webpack config to implement the new error handle.

Thanks.

**Comment by davezuko** [comment]
Hey, thanks for the suggestion! I'd be more than happy to accept a PR for improvements to the error message display! I just pushed a fix for the error message not being displayed in the console, which was simply an oversight -- thank you for catching that. I'm going to close this in favor of a PR, since beside the lack of an error message in the console this is more of an enhancement request than an issue.

Merry Christmas!

**Comment by NE-SmallTown** [comment]
@davezuko Thanks for your reply,I am too busy these days.But I will send a pr if it can work fine with this repo after maybe 1 or 2 weeks.
