### ISSUE TITLE
react-router v4

### ISSUE THREAD

**Issue by message** [davezuko/react-redux-starter-kit#1130]
Hey, I'm really hyped about `react-router` v4. It's way cleaner. Have you seen [presentation](https://www.youtube.com/watch?v=Vur2dAFZ4GE)? Are you planning to switch to v4?

**Comment by mesteche** [comment]
I am working on it in a fork [here](https://github.com/mesteche/react-redux-starter-kit/tree/react-router-v4). I still need to rewrite the tests (I have no clue on how to test this) and find a way of linking the history to redux.
Also I am not sure about the asyncComponent approach, it seems to work but it may not be the best option (I found it [there](https://gist.github.com/acdlite/a68433004f9d6b4cbc83b5cc3990c194)).
If @davezuko is interested, I'll make a pull request.

**Comment by jonricaurte** [comment]
@mesteche that would be great if you made a pr. Most likely would get approved.

**Comment by mesteche** [comment]
I'm kind of puzzled now I've been playing with react-router v4.
I mean, the whole fractal route design may not be relevant with react router v4 anymore.
For instance you can have recursive routes, like in [this example](https://react-router.now.sh/recursive-paths).
Fractal routes are great to represent a tree, but what if your routing doesn't look like a tree but a graph ?
Maybe this is a whole other question and I should open another issue. But since one of the goals of this starter-kit is to remain unopinionated, we should rethink all of this.
Anyway, I'll make a pull request once I get react-router working with redux again.

**Comment by mesteche** [comment]
Some updates:
Last alpha of v4 was buggy and some major API changes are in their way with the release of the upcoming beta. So I will wait until then before resuming on implementing it.

**Comment by jonricaurte** [comment]
@mesteche beta was just released today

**Comment by davezuko** [comment]
Willing to accept a PR for this now that v4 is out and stable, otherwise I will try to get to it when I have time.

**Comment by davezuko** [comment]
Merging into https://github.com/davezuko/react-redux-starter-kit/issues/1217.
