### ISSUE TITLE
createRoutes exported twice

### ISSUE THREAD

**Issue by azizmatmati** [davezuko/react-redux-starter-kit#1131]
Hi, I was just wondering why are you exporting twice **createRoutes** since you got only this function ?
`export const createRoutes = (store) => ({ ... })`
and then at the end.
`export default createRoutes`

**Comment by mesteche** [comment]
I think it because this allows you to import it as the default import as well as a named import.
You can either import createRoutes like this (which imports the default export of routes):
`import createRoutes from 'routes'`
or like this (which imports the named export from routes):
`import { createRoutes } from 'routes'`

**Comment by azizmatmati** [comment]
Yes for sure but doesn't make any sens unless you may want to extend it later and make more than one export on that particular file. anyway it's no a big deal so I'm gonna close this issue !
