### ISSUE TITLE
Question: why is server_host not localhost by default?

### ISSUE THREAD

**Issue by rhysburnie** [davezuko/react-redux-starter-kit#1159]
Hello,

Why is this line setup to use `ip.address()` when the comment next to it seems to suggest a security risk?

`server_host :  ip.address(), // use string 'localhost' to prevent exposure on local network`

Also the only way I can get hot reload to work is when it is set to `'localhost'` - I've seen that mentioned in an old bug, but I'm using the latest and still need to set it to `'localhost'`.

It seems strange that this setting needs to be changed to be able to get hot reloading to works etc, why isn't it `'localhost'` by default with the option for explicit `ip.address()`.

**Comment by davezuko** [comment]
That comment does not suggest a security risk, simply that it is accessible via the local network. The only reason it uses your IP address rather than localhost is so that you can access the server from other devices on your network, such as tablets and phones, for testing. It used to be localhost, but was changed quite a while ago after many user requests.

I don't know why hot reloading doesn't work for you with the ip address; this is the first I'm hearing of any issue. If you think that the usage of an explicit ip address is itself problematic, and not specific to your machine, I'd be more than willing to entertain a PR. Hope that helps, thanks.

**Comment by dbroadhurst** [comment]
FYI - On OSX I need to use 0.0.0.0 to use within a docker container. I'm still in my development environment so no security issues.  Everything works as expected

**Comment by rhysburnie** [comment]
Hi Dave,
RE: "this is the first I'm hearing of any issue"
There are several issues here when you search hot reload in the Issues for example: https://github.com/davezuko/react-redux-starter-kit/issues/955 where a lot of people are saying the same thing that setting localhost works by not with the I address.
Some of them sound related to other services they are running etc but I am not running anyother service or firewall, osMac Sierra latest node.
I don't get reloads with any file when I edit a component, reducer, css file I always have to manually refresh browser.
I can only get it usable by adding a hack:
```
// const ip = require('ip')
const ip = { address: () => 'localhost' }
```
