### ISSUE TITLE
Navigating to /counter directly after deploy:prod does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [davezuko/react-redux-starter-kit#1164]
Hi all,

I just discovered this very nice starter for react redux.

I have an immediate blocker as I want to use this for my next project.

When I run deploy:prod to create the production dist and serve that using the built in server, navigating to the index / route works but when I directly navigate to /counter it throws a 404.

I'm guessing this is a react-router issue, but is there a quick fix?

Thanks very much,
Mark.

**Comment by davezuko** [comment]
This is less a problem than perhaps a misunderstanding. When the bundle is served in live development, the express server forwards all non-asset requests to the home route. This isn't done in production solely because you don't _need_ (and probably shouldn't) run this server in production if its sole purpose is to serve static files. For this, you should use nginx. If you _do_ need to run the server in production to serve assets, just move https://github.com/davezuko/react-redux-starter-kit/blob/master/server/main.js#L43-L53 out of the development environment check.

For nginx, see: http://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page.

Hope that helps.
