### ISSUE TITLE
Files in production cannot find JS file inside folder 2.

### ISSUE THREAD

**Issue by ghost** [davezuko/react-redux-starter-kit#1172]
Hi,

I'm trying to deploy my project into production but I notice that the file inside of `2.` folder isn't found. I found the file that sets this but I can't manage to find any errors about it. The only thing I can provide is this error message shown in the console:

> `GET http://localhost:3000/2./.7fbfba24286f6b55d700.js 404 (Not Found)`

**Comment by Enigma-42** [comment]
Hi,
I've had the same issue, it's because you set the name of the output file : '/'.
This creates a folder rather than a file.

You must change your 'Webpack named bundle' at the end of the file:
```
import { injectReducer } from '../../store/reducers'

export default (store) => ({
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    /*  Webpack - use 'require.ensure' to create a split point
        and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
          dependencies for bundling   */
      const MaterialUI = require('./containers/MaterialUI').default
      const reducer = require('./modules/MaterialUI').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, {key:'materialUI', reducer})

      /*  Return getComponent   */
      cb(null, MaterialUI)

    /* Webpack named bundle   */
    }, 'home')
  }
})
```
So, in my dist/ folder, i have a file named: 0.home.edd4fa5a1d72c57ba5ae.js


You certainly defined this name at '/', like that:
```
/* Webpack named bundle   */
    }, '/')
```
The compiler generate a folder instead of a file in this case ...

**Comment by davezuko** [comment]
Thanks @Enigma-42.
