### ISSUE TITLE
Successfully deployed on heroku but nothing renders

### ISSUE THREAD

**Issue by Robinnnnn** [davezuko/react-redux-starter-kit#1202]
Hey guys, my understanding was that this starter kit would be able to deploy out of the box.

I simply cloned the repo and ran `heroku deploy`. The deploy was successful. However, when I visited the site in the browser, I saw the following error: `CANNOT GET /`. Looks like the server isn't properly serving the static files in production mode.

The server definitely runs as when I type `heroku logs`, it displays `2017-03-27T04:45:54.592832+00:00 app[web.1]: Mon, 27 Mar 2017 04:45:54 GMT app:bin:dev-server Server is now running at http://localhost:49362.`

Any help would be greatly appreciated.

**Comment by davezuko** [comment]
What you want to do is serve the compiled app files from `~/dist` when you deploy it, not run the development server. So you would install dependencies, then run `npm run deploy:prod`, and then either serve those files directly (recommended) or point your application server at them. The latter is what currently happens when you run the express server in production, but you have to make sure to run `deploy` first so that those files exist. See https://github.com/davezuko/react-redux-starter-kit/blob/master/server/main.js#L55-L66.

This may be slightly outdated, but in case the above does not clear things up, somebody wrote an entry in the wiki a while back: https://github.com/davezuko/react-redux-starter-kit/wiki/FAQ:-Frequently-Asked-Questions#heroku-deployment.

Closing since there are a handful of issues around this topic, but let me know if that doesn't help.

**Comment by Robinnnnn** [comment]
Thanks for your input. Turns out `/dist` was being gitignored.... oops.
