### ISSUE TITLE
Upgrade WebPack to 2.x

### ISSUE THREAD

**Issue by SacredWizard** [davezuko/react-redux-starter-kit#1211]
The current react-redux-starter-kit uses 1.x, It would be better if this could be upgraded to 2.x which has ES6 support, creating smaller bundles, better performance and 1.x is being deprecated.

**Comment by davezuko** [comment]
There are a couple of PR's out for this, such as https://github.com/davezuko/react-redux-starter-kit/pull/1189. I would like to get to this at some point, though, since the project has mostly stagnated in favor of more blessed options (Create React App).

Funnily enough, tree shaking is not working correctly in the current 2.x release of webpack (see https://github.com/webpack/webpack/issues/2867). This will be fixed eventually, and make the upgrade worthwhile, but just as an FYI ;).
