### ISSUE TITLE
fails to confirm to eslint spec

### ISSUE THREAD

**Issue by dougvk** [davezuko/react-redux-starter-kit#147]
@davezuko I just enabled linting in my editor and most of the starter kit files fail to conform. i'm going through in my repo and fixing it, but just thought I'd let you know. since I discovered it too late I'm not going to replicate my work on yours. so...yeah just FYI

**Comment by davezuko** [comment]
Referring to all of the non-React files? I'll go through the project today and try to clean them up. Thanks for pointing that out.

**Comment by davezuko** [comment]
Hey these should all be fixed with https://github.com/davezuko/react-redux-starter-kit/commit/3198eb258c02bae612c70cd09aa495746f80db18. I'd been planning on moving the tests outside of `src` for a while now and this was a good chance to do it since there needed to be some mocha/chai/sinon-specific rule changes.
