### ISSUE TITLE
Hot load issue since update

### ISSUE THREAD

**Issue by ioRekz** [davezuko/react-redux-starter-kit#15]
Do you manage to hot reload code ?

I updated my project today to reflect your changes and webpack is unable to hot reload.

[HMR] Cannot apply update. Need to do a full reload!
dev-server.js:19 
[HMR] Error: Aborted because 198 is not accepted

To be sure, I cloned a fresh copy and had the same issue

**Comment by davezuko** [comment]
Hey, I just went and tested a few components and couldn't reproduce this issue. Is there a specific file that's causing you problems?

**Comment by ioRekz** [comment]
No, all of them. I'll continue testing then

**Comment by ioRekz** [comment]
I'm still trying. I observe this only in dev:debug mode. Could you try as well please ? I continue to look for the root problem, thanks

**Comment by davezuko** [comment]
So hot-reloading works in regular `dev` mode, but not `dev:debug`? I'll go try myself; the only thing that `:debug` adds is the redux-devtools, so I'll look into that.

**Comment by davezuko** [comment]
So even if I completely disable the devTool middleware and monitoring component, as long as `redux-devtools/lib/react` is imported hot-reloading breaks. I'm trying to troubleshoot the issue, but in the meantime I've submitted a bug in the `redux-devtools` project: https://github.com/gaearon/redux-devtools/issues/69

**Comment by davezuko** [comment]
I've temporarily fixed this by adding `redux-devtools` and `redux-devtools/lib/react` to the vendor dependencies. Can you please try pulling the latest master branch to see if it's fixed for you?

**Comment by ioRekz** [comment]
fixed for me, thanks ! Just to be sure I understand because I'm new to webpack : this now works because redux-devtools and react-devtools are now bundled in the vendor asset and its not part of the hot reloaded module anymore ?

**Comment by davezuko** [comment]
Hey, there's a bit more in-depth discussion here: https://github.com/gaearon/redux-devtools/issues/69, but the gist of it is:

This starter kit is splitting vendor dependencies, which are listed as just simple strings that Webpack matches against import statements. The key is that Webpack _splits on `/`'s when matching something, meaning the string `"react"` will match _both_ the package `"react"` as well as, unfortunately, `"redux-devtools/lib/react"` because it ends up matching against that last `"react"`. By explicitly defining both `"react"` and `"redux-devtools/lib/react"`, Webpack will know they're two separate packages.

An issue still exists where if you were to bundle anything else that matched `"react"` you'd run into the same issue, so I'm still digging around for another fix, but that's a bit of an edge case at the moment.
