### ISSUE TITLE
Question: code coverage

### ISSUE THREAD

**Issue by fmr** [davezuko/react-redux-starter-kit#157]
`karma-coverage` is included in dev dependencies so it looks like there is some code coverage support. Running tests shows pretty spec output, but no coverage. How does one show code coverage and optionally use the code coverage data for something like coveralls?

**Comment by davezuko** [comment]
Hey, I've been aware of this for a while (https://github.com/karma-runner/karma-coverage/issues/184) but not sure what the solution is just yet. I might try skipping the custom webpack require in favor of a regular glob and see if that fixes it. So unfortunately it won't work as-is, but I'll let you know if/when I figure something out. Thanks.

**Comment by davezuko** [comment]
I got rid of the webpack custom require but the coverage reporter still isn't generating anything, which is strange... I'll keep working on it.

**Comment by davezuko** [comment]
Hey code coverage should work now (https://github.com/davezuko/react-redux-starter-kit/commit/261555ff904b5859e1d1b9e05c0f84d801fb8298), so give it a shot. For convenience I had to rename `~/src/index.js` to `~/src/app.js` so that you don't have to specify all possible sub-folders in the dynamic webpack require.

I'll close this ticket for now, but let me know if you're still having issues.

**Comment by fmr** [comment]
Hi @davezuko, I applied the changes you made in 261555f, and it works nicely :) Brilliant stuff, thanks for the quick response and this fix.

**Comment by davezuko** [comment]
Awesome, glad it works!
