### ISSUE TITLE
Making redux-devtools less intrusive. 

### ISSUE THREAD

**Issue by hairychris** [davezuko/react-redux-starter-kit#167]
It is very obtrusive at the moment, is it worth considering how to fix it?

Option 1
Use it as a chrome extension, then it can be turned off when you don't need it. 
https://github.com/zalmoxisus/redux-devtools-extension

Good: gets out of the way totally unless needed, can be used in production more easily if need be. 
Bad: can't use anywhere that doesn't allow chrome (although will work on chrome mobile)

Option 2
Set visible onload to false: <DevTools monitor={LogMonitor} visibleOnLoad={false} store={store} />
https://github.com/gaearon/redux-devtools/issues/44

Good: again get's right out of the way, can be brought back with a simple ctrl+h
Bad: we need to communicate to developers that ctrl+h will bring up the developer panel

**Comment by davezuko** [comment]
What about reverting the default `dev`/`start` command to not include devtools, and then optionally enabling it with `--debug` or `dev:debug` (how it used to be)?

**Comment by fuczak** [comment]
Seems like a matter of preference, maybe a [poll](http://strawpoll.me/5962213) would be a good idea to see what's generally preferred?

**Comment by davezuko** [comment]
@hairychris thinking about it, I'm a much bigger fan of option 2 since it's local to the starter kit, but I'd prefer to have it be at the CLI level. That said, I'll probably create a configuration option that people can easily change to set the onLoad visibility of the devtools.

Please refer to https://github.com/davezuko/react-redux-starter-kit/issues/168 for more discussion on this.

**Comment by hairychris** [comment]
Sounds good to me, thanks for looking at this.
