### ISSUE TITLE
Default devtools behavior, enabled or disabled?

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#168]
**Please vote in the comments below.** An explanation around your preference would be nice, but is not necessary.

This is to determine whether the base `npm start` command should run with devtools enabled or disabled. The starter kit currently has devtools **enabled by default**, where they can be optionally turned off by using `npm run dev:no-debug`.

Switching this would invert the commands to how they used to be in the early days of the starter kit, so `npm start` would run the webpack-dev-server but not include devtools, and they could be enabled with `npm run dev:debug`.

This goes back to the old question of: how often do you use devtools? Do you find yourself disabling/hiding them more often than not? Or do you use them frequently and want to keep them as the default behavior?

Thanks everyone.

**Comment by fuczak** [comment]
Well either everyone but me hates DevTools or someone is dedicated enough to switch IP several times and mess up with the vote. Isn't it a bit strange that the vote counter stayed at 2 for few hours and now suddenly it's at 80?

**Comment by davezuko** [comment]
@fuczak something must be messed up. We can just do the poll in this issue, I'll update the description.

**Comment by kyleect** [comment]
Personally my preference would be hide by default via `visibleOnLoad=false` so we can toggle visibility when needed. If this is not an agreeable solution then I would vote for disabling by default.

**Comment by davezuko** [comment]
If we go with setting visibleOnLoad to false then I'd probably just add a key for that option in the project configuration so it's easier to switch to the desired functionality. Might not be bad.

**Comment by fuczak** [comment]
That sounds resonable. For the sake of expressing my thoughts I'd personally go with `visibleOnLoad=true` since I'm using DevTools all the time.

**Comment by inooid** [comment]
I find myself hiding it more often than not, but honestly, one of the reasons I wen't with this starter kit was to get a feel of how the `devtools` were implemented. So for new people it's probably the best way to get them on board. It will give that "WOW"-effect when you launch the starter-kit and see the devtools up and running.

So I think it depends on where **YOU** want to focus on with this starter-kit. Do you want people to get on board up and running with it, or do you want to supply the people that already work with it. I never ran `npm run dev:no-debug`, because I'd rather hide it and open it when I have to.

**Comment by davezuko** [comment]
I agree @inooid that it's more about highlighting the starter kit's functionality than customizing it for users already familiar with the devtools. As often as I personally hide/disable devtools, I think it makes sense to keep them enabled and visible by default, and then people are free to customize it as they see fit; it's fairly trivial.
