### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by neverfox** [davezuko/react-redux-starter-kit#195]
Is there any interest in setting up the kit to use [CSS Modules](http://glenmaddern.com/articles/css-modules) instead of the basic SASS style sheets it currently uses? I know this is an opinionated area, what with all the various takes on styling React (e.g. the inline vs CSS debate). It's a fairly minor change to webpack configuration and I don't mind submitting a PR if the answer is 'yes', but I thought I would gauge the interest first.

**Comment by davezuko** [comment]
I'm not opposed to it, but at the same time I'm also trying to keep this starter kit as slim as possible so it doesn't become a kitchen sink like a lot of the other boilerplates available. That's not exactly applicable to CSS modules since they replace the Sass stylesheets, but it does (imo) add another barrier to entry for new users (myself included).

I'd be curious to see what other people have to say about this.

**Comment by loklaan** [comment]
I've created a branch, with css-modules, to play around in. I'm likely to soon use it in a product, so it will be tested. :)

https://github.com/loklaan/react-redux-starter-kit/tree/css-modules

**Comment by neverfox** [comment]
One of the nice things about it is that you can set it up right alongside the current SASS configuration and even use it while you're also using an inline approach like Radium or react-look. That's part of the beauty of Webpack loaders.

**Comment by davezuko** [comment]
@neverfox I'd be open to a PR for this if you're up for it. I can't decide which would be better to demo though, if we keep it alongside the sass configuration (which would probably be wise).

**Comment by vaselok** [comment]
Guys, are you planning to implement sass/css bundling to one file out of the box?

**Comment by davezuko** [comment]
@vaselok yes, it's in the works here: https://github.com/davezuko/react-redux-starter-kit/pull/230

**Comment by davezuko** [comment]
This has been implemented.

**Comment by vaselok** [comment]
awesome!
