### ISSUE TITLE
Site routes not working on server

### ISSUE THREAD

**Issue by OKNoah** [davezuko/react-redux-starter-kit#220]
Hi,

I've created a site that works well locally. However, when I load it to Heroku, the routes don't work as expected. Linking to `/search` from the home page works fine, but not when navigated to directly or refreshed.

I have also tried making my own node server to access `/dist/client` and serve that, but then I get many errors in the browser console about being able to connect to socket-js.

Any insight would be appreciated.

**Comment by JuoCode** [comment]
Example with expressjs:

```
//...
//...
app.get('/*', function(req, res){
  res.sendFile('public/index.html');
});
```

The second question, Specify the `NODE_ENV=production` when compile

**Comment by davezuko** [comment]
@OKNoah I don't use Heroku so I can't offer any detailed explanation for their service, but you most likely need to setup your web server to always serve the root `index.html` file regardless of the endpoint hit. If everything is already being forwarded to your express app, then you only need to do what @JuoCode posted, otherwise if that's not yet setup you'd have to configure nginx or whatever other web server it is you're using.

That said, unless you actually need the express server for something (i.e. an API) then I generally just point the web server directly at `dist` and bypass an app server altogether.

**Comment by OKNoah** [comment]
@davezuko Yes, I'm now having to make my own server to host the `/dist` stuff. However, this throws server-side rendering out the window, unless I learn how to set that up on my own as well. Still, I am running into basic problems, like things in my `src/assets` folder are not available after I compile as `production` environment.

Also, I am not using nginx. Heroku simply runs the app with whatever environmental variables you give it.

**Comment by OKNoah** [comment]
Maybe I'm misunderstanding. Is there an production server in this repo or not?

**Comment by davezuko** [comment]
@OKNoah I got an email about a comment you posted but no longer see it. To answer it: no, there currently is not a production server in this app. Out of the box it's able to be served statically from `~/dist` from a web server, but if you need to serve it from an app server like for Heroku then you'll need to set that up yourself (again, probably just what @JuoCode posted would suffice).

**Comment by davezuko** [comment]
Closing this for now (moving it to https://github.com/davezuko/react-redux-starter-kit/issues/221). I've updated the README to include a bit more detail around deployment, and I'll continue to improve upon the documentation once https://github.com/davezuko/react-redux-starter-kit/issues/221 gets moving; feel free to discuss this further there if necessary.
