### ISSUE TITLE
Hot reload in dev:debug doesn't work on Windows

### ISSUE THREAD

**Issue by SACRD** [davezuko/react-redux-starter-kit#23]
Hello! I was trying to deal with your starter kit. It works like a charm on Debian. But on Windows 7 (x64) small change makes the whole page to reload.

**Comment by davezuko** [comment]
Hey, do you experience this with any other Webpack setups? Im curious as to whether or not it's related to the starter kit or something with Webpack on windows.

**Comment by SACRD** [comment]
I'm using node 0.12.7.
Hot reload doesn't work properly in dev:debug only. 

So it's probably like #15

**Comment by davezuko** [comment]
Oh interesting - are you on the latest master branch? This one's going to be a bit tricky to debug since I don't have access to a Windows machine, but if you're still seeing the issue even with the fix for https://github.com/davezuko/react-redux-starter-kit/issues/15 then I'll try to do some more digging.

**Comment by SACRD** [comment]
Just cloned master branch again - this works fine now.

**Comment by davezuko** [comment]
Awesome, glad it's fixed. Closing this for now then, let me know if you encounter any other issues.
