### ISSUE TITLE
Add favicon support

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#234]
This should work out of the box. Submissions/ideas welcome!

**Comment by N8-B** [comment]
@davezuko First of all, thanks for all the work you've put into this. Since the html-webpack-plugin is being used couldn't we just pass 'favicon' into the configuration options in the _base.js and then add the favicon path/filename in the config index for users to change if needed? I'm just getting started with this kit so this may be a naive approach.

**Comment by N8-B** [comment]
Here's what I've done to add a favicon on a personal project.

**Favicon support:** [branch](https://github.com/davezuko/react-redux-starter-kit/compare/master...N8-B:favicon_support) 

I'm sure there's a smarter way to do this for the kit, but this covers my immediate needs.

**Comment by mtsr** [comment]
I like it, how does it end up in the compiled version? Just `favicon.ico` in the root and no links in the html?

**Comment by N8-B** [comment]
@mtsr Yeah, just `favicon.ico` in the root and no links in the html. It's not a robust solution, e.g. apple-touch icons, but it does the trick for basic use cases. Another option could be to use an html template, [for example](https://github.com/N8-B/cw-kata/blob/master/templates/my_wp_template.html#L10), in order to add a link in the html.

**Comment by davezuko** [comment]
@N8-B Thanks for the example, I didn't have anything more complex in the mind, but just didn't have a favicon to actually use haha. If somebody has any options to contribute it would be appreciated.

I also thought about possibly just creating a `public` folder in the root and putting the favicon in there (and referencing it correctly from HtmlWebpackPlugin). That way you could add more static assets as needed without having to copy non-imported assets from src -> dist.

**Comment by mtsr** [comment]
I don’t know about this. I feel having static content used without require is becoming more of an anti-pattern with webpack.

**Comment by justingreenberg** [comment]
@davezuko let's just use react favicon?

![image](https://cloud.githubusercontent.com/assets/1539088/11769200/ab39f862-a1af-11e5-9550-ad0289b23be2.png)

https://facebook.github.io/react/favicon.ico

**Comment by davezuko** [comment]
Sure, sounds good to me

**Comment by justingreenberg** [comment]
>I also thought about possibly just creating a public folder in the root and putting the favicon in there (and referencing it correctly from HtmlWebpackPlugin). That way you could add more static assets as needed without having to copy non-imported assets from src -> dist.

@davezuko i agree, this is a good opportunity to create a folder for static assets such as index.html, favicon.com, robots.txt, etc.

**Comment by davezuko** [comment]
@justingreenberg what do you suggest, just something like `public` or `static`?

**Comment by justingreenberg** [comment]
@davezuko how about `assets`?

**Comment by davezuko** [comment]
@justingreenberg I just want to make sure I'm clear on the design:

Are you imagining this as a root directory (as I am)? If so, I'm still curious about the proposed workflow. If you were to serve an application with this design, you'd have to point the web server to _both_ `static` and `dist`, which seems kinda silly. Is there a better solution that I'm missing?

If I'm wrong in this assumption, and it's a folder within src (`~/src/static`) then are those files copied over upon compilation?

**Comment by justingreenberg** [comment]
i was initially thinking a folder within `src/assets`, but it could also be in root directory—since we're using webpack, all assets should really be passing through a loader and bundled before hitting the build target (`./dist`). `webpack-dev-middleware` will handle serving during development and in production it would be handled by express (or simple static file server ie. s3) 

does that make sense?

**Comment by davezuko** [comment]
Yes, thanks. My only question was with regard to the `robots.txt` and similar files, since I don't understand how those would get processed by webpack unless you were using something like react-helmet (if I understand that package correctly).

**Comment by justingreenberg** [comment]
can we use [webpack/file-loader](https://github.com/webpack/file-loader) to pipe static files through webpack?

**Comment by davezuko** [comment]
Oh, probably, I'll take a stab at it. And ok, thanks for the heads up.

**Comment by davezuko** [comment]
Closing this in favor of https://github.com/davezuko/react-redux-starter-kit/issues/234, we can move the discussion there. Favicon will be added once this is all sorted out.
