### ISSUE TITLE
Follow ducks-like architecture

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#248]
I don't agree with the naming conventions, but overall it would be nice to group flux pieces together (constants/reducers/actions).

**Comment by justingreenberg** [comment]
agreed! i'm actually the one who [initially restructured erik's universal example](https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/redux). i would propose something similar without the naming conventions (ie. namespacing constants for action types is unnecessary)

this is roughly how my projects are structured:
```
/redux
    /middleware
    /modules   [grouped redux logic aka "ducks"]
    /selectors [reselect helpers - probably not necessary for starter-kit]
    createStore.js
```

**Comment by davezuko** [comment]
Cool, I also really like the `modules` naming convention over `ducks` or whatever else. Thanks for the link, too.

On an unrelated note, I've been thinking about switching away from the airbnb-config base to something closer to a mix of ract/standard. Any opinions on this? Biggest thing would probably just be removal of semi colons.

**Comment by justingreenberg** [comment]
:+1: rackt config

```json
"space-before-function-paren": [ 2, { "anonymous": "always", "named": "never" } ]
```

are you gonna be ok with this one? lol

**Comment by mtsr** [comment]
Removal of semi-colons still feels wrong to me. Call me a classicist :)

**Comment by davezuko** [comment]
@justingreenberg I will fight that rule until the day I die; it separates function definitions from invocations, and just makes the code look so much nicer.

@mtsr I was the same way until my new team forced it upon me haha. The other big debate now is "use trailing commas or not" or, if you're nuts like me, "leading commas?!"

**Comment by davezuko** [comment]
@justingreenberg could you offer up an explanation as to what exactly lives under `/middleware`? I thought it would be actual middleware (i.e. for the redux life cycle), but your comment about moving the DevTools component there threw me off.

**Comment by justingreenberg** [comment]
@davezuko i'm sorry i can see how that was confusing  `/middleware` is totally for redux lifecycle stuff! 

so using the `createDevtools` HOC over monitors instantiates a container, but we still have to import and invoke an instance method to inject the middleware hooks into the redux store. so it's not _really_ a container, it's more like a factory (which is why i proposed renaming to `createDevtools.js`)

maybe something like:

```
/redux
    /middleware
    /modules   [grouped redux logic aka "ducks"]
    /devtools/createDevToolsContainer.js
    /devtools/createDevToolsWindow.js
    createStore.js
```

imho, this just seems much more intuitive and puts some distance between project code and devtools

**Comment by davezuko** [comment]
Thanks for the explanation. I actually missed the fact in your previous comment that everything was nested within a `redux` folder... I'm not actually sold on that just yet, but I'm going to run out for a few minutes and mull it over. The big thing is that `modules` are now nested in e.g. `~/src/redux/modules/counter`, so I might like to pull that up a level (`~/src/modules/counter`).

**Comment by justingreenberg** [comment]
the case for a `redux` folder is to establish a clearly defined boundary between state management and presentation, with the added benefit of (mostly) encapsulating redux integrations

i feel like many redux projects end up spreading out state logic between connected containers/components, devtools, etc. which is probably muscle memory from using flux with a bunch of stores... it ends up making things more difficult to reason about than they need to be with a single store. 

since we're talking about using "ducks" (redux modules!!), that boundary is actually within reach

```bash
./src
    /components
    /containers
        Root.js  # point of contact for devtools, code unchanged
    /layouts
    /routes
    /redux *
        /middleware
        /modules
            counter.js
        /helpers
            createDevToolsContainer.js
            createDevToolsWindow.js    # uses createDevToolsContainer.js
            createReducer.js
        configureStore.js
    /styles
    /views
    app.js  # point of contact for store / redux router
    index.html
```

the only points of contact between **./redux** and the application are Root container (for devtools), any other connected containers, and app.js (an idiomatic redux app could thread action creators via props)

 some food for thought... i support the restructure and "redux modules" either way!
