### ISSUE TITLE
Reduce webpack output

### ISSUE THREAD

**Issue by patrickheeney** [davezuko/react-redux-starter-kit#267]
In webpackdev, we currently use `stats: { colors: true }` which is pretty verbose. Webpack supports other options that are more favorable: `stats: 'none' 'errors-only' 'minimal'`. No PR attached as it is a simple change and I have a 33% chance at guessing the right one for the PR. 

Related: https://github.com/webpack/webpack/pull/1323

**Comment by davezuko** [comment]
Yeap, great point, I actually have this in the works! In one of my other projects I created a `compiler_stats` configuration that is used for webpack in the compiler/dev-server/karma, so this will be fixed when that's added/configured.

**Comment by davezuko** [comment]
Resolved with https://github.com/davezuko/react-redux-starter-kit/pull/268

**Comment by mtsr** [comment]
With the difficulty of debugging webpack problems as it is, I don’t know whether ‘hiding’ more output by default is a good idea. I know the current loggin helped me solve a bunch of problems.

I feel this needs a good description in the readme of how to get more output, otherwise it’s not a clear advantage to me.

**Comment by patrickheeney** [comment]
All this does is seemingly remove the chunking information. I am not entirely sure how useful that is for debugging?

**Comment by mtsr** [comment]
Ah, sorry for the misunderstanding. Sounded like you were trying to cut down webpack output by a lot.

**Comment by patrickheeney** [comment]
The chunking is the vast majority of the output. I personally switched this to `minimal`, so I can still tell it is doing something, but even `errors-only` is helpful. I am not sure how #268 changes this yet as I have not tested, but it only looks like chunking is turned off.

**Comment by davezuko** [comment]
@patrickheeney this is how it looks using the new `compiler_stats` configuration in `~/config/index.js`:

<img width="631" alt="screen shot 2015-12-12 at 9 44 09 am" src="https://cloud.githubusercontent.com/assets/6439050/11762457/0057cf3c-a0b5-11e5-8898-958685def5d0.png">

This looks _very_ similar to what you'd get with `minimal` (but looks better IMO). Is there something I'm missing? Using `minimal`:

<img width="632" alt="screen shot 2015-12-12 at 9 45 53 am" src="https://cloud.githubusercontent.com/assets/6439050/11762463/2a0c69f0-a0b5-11e5-9a00-b618d7b9ff38.png">

**Comment by davezuko** [comment]
Also @mtsr I should probably add a note about how to make logging verbose in development, but I've personally been using the ^^ output without any issues. Production builds are configured to display _all_ chunk information, though maybe it would be better to differentiate between live development builds and static builds, rather than by environment.

**Comment by patrickheeney** [comment]
@davezuko Sorry for the confusion. I switched to `minimal` when I opened the PR. I simply haven't updated to the latest version yet haha.
