### ISSUE TITLE
Incremental builds time

### ISSUE THREAD

**Issue by sars** [davezuko/react-redux-starter-kit#316]
Hi there,
How long do incremental builds take usually?
It takes 800-1000ms on my computer.. on fresh installation of react-redux-starter-kit
Is it normal? Will it increase too much when code base grows?

**Comment by davezuko** [comment]
I guess it all depends on your system, but are you seeing this as abnormal compared to other projects? It's going to be heavier than just vanilla webpack due to the number of transforms being applied, but I've yet to hear of any real performance concerns.

<img width="644" alt="screen shot 2015-12-15 at 4 53 51 pm" src="https://cloud.githubusercontent.com/assets/6439050/11825336/75dd43ce-a34c-11e5-80b7-84b56e9d604c.png">

**Comment by davezuko** [comment]
Also, if you happen to know of any common ways to improve the performance of webpack during development builds, as @justingreenberg pointed out with the `cheap-eval-source-map`, we could work on integrating them.

**Comment by justingreenberg** [comment]
with respect to babel/webpack integration, there are a couple of other optimizations to mention:
 - caching transformations on disk using `cacheDirectory`
 - disabled automatic injection of runtime helper functions (via plugin declaration in loader query)

**Comment by davezuko** [comment]
We're doing both of those, so I'll have to keep my eyes out for anything else that we can do to speed up builds.

**Comment by sars** [comment]
@davezuko Thank you for answers, 800ms is ok for me now, i was just concerned that this time will increase significantly when codebase will be larger
