### ISSUE TITLE
Should We Deprecate `npm run dev:nw`?

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#321]
As pointed out in https://github.com/davezuko/react-redux-starter-kit/issues/317 by @sars, would this be a good move for the starter kit? I've personally never use the `dev:nw` command, and am not sure how many people actually do. If it's not a critical feature, I'd suggest we consider eliminating it from the core of the repo and point users to the extension if they want a similar experience.

Note: The sidebar dock would still remain.

**Comment by mtsr** [comment]
I do use it, since I often work on just the 13” screen at home, but the extension might be a good alternative, although I haven’t tried.

**Comment by davezuko** [comment]
Ah ok, thanks @mtsr. You're a pretty core contributor so I don't want to remove this if you've found it useful. That said, I'd be curious to see what you think of the extension; I'll give it a try myself.

**Comment by sarunast** [comment]
I am using it as well. But the main reason for me that dev tools always appears on screen if I refresh the window, if by default somehow it would be possible to hide and open it with ctrl+h, then I wouldn't need the dev window. Basically my dev window is clean but whenever I am interested in states I peak in the other window, I don't want to see them all the time or always hide it with ctrl+h.

**Comment by davezuko** [comment]
@sarunast there is a way to do exactly that: https://github.com/gaearon/redux-devtools/issues/44#issuecomment-137578200

**Comment by sarunast** [comment]
@davezuko thanks you very much. I was thinking that there should be an easy way.

**Comment by neverfox** [comment]
I *only* use `dev:nw` lol (ok, not always). When doing mobile-first development, it's annoying to have to hide the devtools on each hard refresh and it's unreadable, in any case, on small viewports.

**Comment by neverfox** [comment]
Is your main concern the extra code needed to support it?

**Comment by davezuko** [comment]
@neverfox that relates to an old issue I posted where I wanted to set the default visibility of the devtools to hidden, but was outvoted. Maybe this would be a good chance to make it a configuration option.

And yeah, it's just that it's yet more code in the starter kit. I guess it's not a huge deal, and from what I'm hearing people do use it, so I'm open to keeping it in the project.

**Comment by mtsr** [comment]
With at least two solutions (extension and default hiding + hotkey) don’t feel the need to keep it for me. I still like having it, though I think the extension will replace it nicely for me.

**Comment by patrickheeney** [comment]
I am personally using https://www.npmjs.com/package/redux-logger and the code below in my apps. I just needed a log rather than an interactive dev tool that is a bit hard to shuffle around while working.

```
if (__DEBUG__) {
  window.appDebug = require('debug');
  window.appDebug.enable('app:*');
}
```

**Comment by janders223** [comment]
I use nw exclusively, as @mtsr points out, on just a 13" screen you need every piece of real estate you can get.

**Comment by justingreenberg** [comment]
if you want to play around with the extension this is a good side for it since the store is still attached in production (which is pretty cool, since it's still completely transparent to anybody without the extention) http://erikras.github.io/redux-form/
 
Using in devtools (docked to right):
![screen shot 2015-12-16 at 12 42 49 pm](https://cloud.githubusercontent.com/assets/1539088/11848798/8c150fea-a3f2-11e5-84bd-86041c4897d2.jpg)

Using from omixbox:
![image](https://cloud.githubusercontent.com/assets/1539088/11848824/badfeb4c-a3f2-11e5-9f24-adc2910990b6.png)

although this is probably the most elegant solution for the time being, it is pretty opinionated. 

a few weeks ago i started working on a babel transform to inject devtools at runtime, but decided to wait for some open issues to be resolved. it looks like they are at this point, so maybe i could wrap it up over winter break :)

**Comment by janders223** [comment]
Thanks @justingreenberg I will def check that out!

**Comment by neverfox** [comment]
I would definitely switch to an extension that kept devtools off of the viewport!

**Comment by davezuko** [comment]
Sounds like the answer is no for now, and we can get some documentation in place to refer people to the extension if it's a more fleshed out solution.
