### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by 3went2** [davezuko/react-redux-starter-kit#34]
I got 'Segmentation fault: 11' after I run `npm run dev`. Did I miss something?

<img width="591" alt="screen shot 2015-08-26 at 23 08 16" src="https://cloud.githubusercontent.com/assets/1403911/9497418/6db67898-4c47-11e5-9e92-3328483852e4.png">

**Comment by davezuko** [comment]
Ahhhhh god I had that problem a long time ago but don't remember what caused it. I don't think you're doing anything wrong, but I don't know what's causing it off the top of my head. Any chance you could give it a go on io.js? What about the other tasks? Does it specifically occur when running the dev server?

It should be working on node `^0.12.0`, and I haven't heard anyone state otherwise until now. I'll start searching around to see if I can find anything.

**Comment by gaearon** [comment]
If you changed node versions recently, or if you copied the project from a machine with a different architecture or OS version, you may try running `npm rebuild` to recompile the binary packages.

**Comment by 3went2** [comment]
@gaearon It still doesn't work after I run `npm rebuild`. 😭

**Comment by 3went2** [comment]
@davezuko `npm run compile` is okay, but `npm run dev:*` not. I have tried on node `0.12.4` and `0.12.7`. I have not tried on io.js yet.

**Comment by 3went2** [comment]
I removed `node-sass` and reinstalled it, and then it works. Guys, thanks.

**Comment by davezuko** [comment]
Glad you figured out a fix, but curious why `npm run rebuild` didn't fix things.

**Comment by 3went2** [comment]
@davezuko I don't know either. (;´༎ຶД༎ຶ`)
