### ISSUE TITLE
Help to serve the static assets in the development mode

### ISSUE THREAD

**Issue by geohuz** [davezuko/react-redux-starter-kit#340]
I have a react component with an img tag and it refers to an assets file which I put into assets/images,
when I start the npm start I saw the 404 error, if I start with the npm run compile and the component is rendered correctly. I have tried to tweak the configuration files to make it work in the dev mode but failed, could anybody kindly point out how to make it work?

Thanks!

**Comment by davezuko** [comment]
Two things:

1) If you're using an image, you probably want to be making use of the file/url loaders from webpack by directly importing them into your application. The assets folder (which has since been renamed to "static" for clarity) is only meant for files not directly used in the application code.

2) That said, I _did_ just make an update (https://github.com/davezuko/react-redux-starter-kit/commit/b1bb27addc6f9b519fa8e1ffb3271c961cd0f460) that allows these static assets to be referenced during live development without having to compile first. That said, you definitely should try to stick with option #1 as much as possible.

**Comment by geohuz** [comment]
All right, I got it, thanks!
