### ISSUE TITLE
Use .js instead of .jsx

### ISSUE THREAD

**Issue by Amorino** [davezuko/react-redux-starter-kit#37]
A lot of examples and boilerplates, even the Redux official examples are not using .jsx for components.

**Comment by davezuko** [comment]
I'd like to hear more on this before just changing all the files in the project. Personally, the `.jsx` extension has been helpful since my IDE can make assumptions based off the of the file extension, and even simple things like file icon extensions help separate what in a project is a react component and what's just vanilla JS, for lack of a better term.

**Comment by nhagen** [comment]
+1 for `.js`. I don't think its that important, but I get the sense that the community is more and more not making the distinction. JSX isn't vanilla js, but neither is ES6/ES7, and we're not using `.es6`. The pattern seems to be that if its getting transpiled down to vanilla js the `.js` extension is okay.

**Comment by davezuko** [comment]
@nhagen I really like the argument about `.es6`, as I've never been a fan of that extension. Personally the only thing holding me back right now is the nice file icons I get in my IDE, but thinking about it that's a pretty silly reason to make decision for a starter kit.

`.js` it is, I'll update the project later. That said, I do have one more question: what about naming conventions? A lot of React projects seem to be going with ProperCased file names for components, which is a divergence from the previously popular dash-separated names. My team has actually switched to the former, since the file name then matches the class name, but I'd be curious to hear what others think.

**Comment by nhagen** [comment]
hm. I've always used thisCamelCase, but it looks like facebook uses [ProperCase](https://github.com/facebook/react/blob/master/examples/server-rendering/jsapp/src/App.js), so thats probably what everyone should be doing.. Crap.

**Comment by davezuko** [comment]
Updated all `.jsx` files with https://github.com/davezuko/react-redux-starter-kit/pull/62.
