### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by nhagen** [davezuko/react-redux-starter-kit#372]
I'm not able to set breakpoints in chrome or firefox off master. Can someone confirm?

All of my stack traces are referencing `evals` as well. Seems like something is wrong with source maps?

**Comment by shanewho** [comment]
Same here. Seems like sometimes my breakpoints work if I have a `debugger` _somewhere_ in the file. Not sure what's going on. I thought it might be hot reloading at first but I disabled that and still don't have breakpoints. I'm `console.log` and `debugger` debugging for now..

**Comment by shanewho** [comment]
Here you go:
https://code.google.com/p/chromium/issues/detail?id=459499

`any script built with webpack and using the devtool config setting eval-source-map`

This kit has the setting to `cheap-module-eval-source-map` (in build/webpack/_development.js) which also seems to not work. I just tried `source-map` and I have breakpoints again! Some other options might work too, I haven't tried:

https://webpack.github.io/docs/configuration.html#devtool

**Comment by davezuko** [comment]
Yeah I was having this issue the other day, thanks for pointing that out @shanewho. Might have to remove the cheap devtools until it works correctly.

**Comment by netpoetica** [comment]
Note: this is not glorious but it will work.

Add this script to your scripts array in your package.json
```
    "magic": "npm run compile && node -r dotenv/config bin/server",
```

and then in your root dir type:

```
npm run magic
```

This will give you a couple of warnings but you can work around them. Then, your source files can be debugged by navigating to webpack://./src/ dir in the Chrome sources panel.

You have to compile first because if you don't have a dist directory - and you won't, because if you are always using the dev server, it's just hot reloading - it wont comile.

**Comment by davezuko** [comment]
Temporarily reverted to using `source-maps` in development until a better solution can be found.

**Comment by duro** [comment]
@davezuko @netpoetica @shanewho @nhagen did any of you figure out where to report this bug?
