### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by juanda99** [davezuko/react-redux-starter-kit#373]
I'm using your kit with react-intl for localization. 
If you consider it doesn't affect the primary goal of the project (to remain as unopinionated as possible), I could make a PR so it could support several languages out of the box.

**Comment by vire** [comment]
@juanda99 +1 for i18n support.

Do you have a good experience with react-intl?

**Comment by rsilvestre** [comment]
@juanda99 :+1:

**Comment by juanda99** [comment]
@vire No experience with react-intl. In fact right now I'm unable to change language for the options in a select!!!! 
My modifications:
https://github.com/juanda99/react-redux-starter-kit/commit/15f71395961b817322f3847818bedb08313d4841

**Comment by davezuko** [comment]
Hey @juanda99 this is really cool, and I definitely appreciate the work, but I think it may be a bit too much to include in the starter kit. It already feels somewhat bloated to me, even without this, so I'm trying to work on removing rather than adding stuff for the time being. If you'd like to maintain a personal fork of this, however, I'd be more than happy to add an "examples" section to the README for people to check out your work.

**Comment by juanda99** [comment]
Sounds good for me :-)

**Comment by davezuko** [comment]
Great, closing this in favor of https://github.com/davezuko/react-redux-starter-kit/issues/386, where there's a task to add documentation around example projects/functionality, and I'll point to this issue and your project.
