### ISSUE TITLE
Inclusion of redux-state-history

### ISSUE THREAD

**Issue by terakilobyte** [davezuko/react-redux-starter-kit#380]
[This](https://github.com/inakianduaga/redux-state-history) is pretty slick.

Would including it in the project be something that's desired? If so, I can work on a PR.

**Comment by davezuko** [comment]
:+1: that looks super cool. While I'd definitely use it in my personal projects, I'm slightly torn just because I don't want to diverge _too_ much from the core redux offerings, but at the same time including _both_ this and the default devtools seems to introduce too much bloat. If you have any good ideas for how to cleanly implement this I'm totally open to it.

**Comment by SimonSelg** [comment]
Well, there could be additional section in the README with links to additional cool/useful tools/libraries that you *could* use in your projects. I think that'd be a nice thing to have, it'd help people discover awesome stuff without being forced to use it.

What do you think?

**Comment by davezuko** [comment]
:+1: @SimonSelg , but this honestly looks cool enough to integrate from the outset, though not sure what you and @terakilobyte think. /cc @neverfox @justingreenberg @mtsr in case they have any opinions.

What I'd _really_ like to do is focus time on improving the README so it can act as more of a guide/resource than just an "about this project" page. That would include things such as this, tools such as reselect, and also links to projects that use this kit. Maybe I'll draft up a milestone at some point.

**Comment by SimonSelg** [comment]
In fact I tried to integrate it into one of my projects a few hours ago, because it really is cool.

I've run into two problems:
- Currently there seems to be an issue with one of it's dependencies - react-dropzone - which expects the children property to be something else then redux-state-history supplies.
- We can't just throw the nice monitor component in the root container, or at least I wouldn't do it. That's because the monitor component uses `position:fixed; bottom: 0; width: 100%;` , meaning it's always at the bottom, overlaying/blocking the lower ~70px of the app. 

Besides from that (the first one is easily fixable provided that the author reacts to pull requests), not sure tho what to do about the second point. Maybe it's just me who dislikes that behavior tho (I removed it from my project until I find time to figure out a good solution).

**Comment by davezuko** [comment]
Fair points; I think for now a good solution would be to at least document it in the README. From first impressions the normal dock monitor appears to be more useful from a developer perspective; it's saved me countless hours of debugging weird state/action issues, but this tool looks great from a QA/testability perspective.

**Comment by neverfox** [comment]
And I believe devtools will be integrating the slider soon anyway.

**Comment by SimonSelg** [comment]
@davezuko Yep that's true, but I think the focus seems to be different from the devtools. For state/action issues I'd still use the devtools, but the export/import and replay functionality sounds awesome for use cases when you're working together with other people. When someone refers to some state of the app, instead of telling you exactly how to reach it, you can just let him export the state history, then import it and replay it.

**Comment by davezuko** [comment]
Cool, closing this in favor of https://github.com/davezuko/react-redux-starter-kit/issues/386, where we can at least add some documentation to point people to this devtool.
