### ISSUE TITLE
App may be broken with Babel ^6.4.0

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#405]
See: https://github.com/feross/standard/issues/372 and https://github.com/babel/babel/pull/3225

Haven't had time to test this yet, busy triaging code bases for work :(

**Comment by roryokane** [comment]
The kit is indeed broken right now. I just tried to create a new app from this starter kit, and I got two errors of this type when I ran `npm run`:

```
ERROR in ./src/containers/Root.js
Module build failed: SyntaxError: /path/to/my-project/src/containers/Root.js: A semicolon is required after a class property (9:3)
```

And instead of http://localhost:3000/ showing the app, it just showed the plain text “Not found”.

I was able to fix those two syntax errors by adding semicolons in [`src/containers/Root.js` line 9](https://github.com/davezuko/react-redux-starter-kit/blob/2e8b3d073c7319e07601aa3f482e0d06dc1513e9/src/containers/Root.js#L9) and [`src/views/HomeView.js` line 19](https://github.com/davezuko/react-redux-starter-kit/blob/2e8b3d073c7319e07601aa3f482e0d06dc1513e9/src/views/HomeView.js#L19).

**Comment by neverfox** [comment]
Ugh.

**Comment by davezuko** [comment]
Still swamped w/ work but will fix this when I get a chance. <3 Babel.

**Comment by davezuko** [comment]
Hotfixed with: https://github.com/davezuko/react-redux-starter-kit/pull/407
