### ISSUE TITLE
Integrate chai-enzyme

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#480]

**Comment by marr** [comment]
Would this task involve removing `karma` from the testing flow? I see there is a `mocha-loader` for webpack[-dev-server] which I am trying to integrate now.

**Comment by davezuko** [comment]
I really don't have a problem with Karma, so I'd like to keep it if we could (having never used something like jsdom) but if you have any arguments for scrapping it I'd love to hear them.

**Comment by jbinto** [comment]
I'm trying to help [mxstbr/react-boilerplate](https://github.com/mxstbr/react-boilerplate/issues/79#issuecomment-174238581) migrate from mocha/jsdom to Karma, and they already have chai-enzyme set up.

I can't figure out how to integrate chai-enzyme and karma. I'm not very knowledgeable when it comes to how `require` works, ES modules, karma plugins, etc. so I'd be interested to see if you are able to figure it out.

If you're interested take a look at the issue here: https://github.com/mxstbr/react-boilerplate/issues/79#issuecomment-174238581
