### ISSUE TITLE
Directory structure: "Views" thought process

### ISSUE THREAD

**Issue by jasonkylefrank** [davezuko/react-redux-starter-kit#486]
Hello!

Your (excellent) docs explain that you have 4 types of React components in your directory structure: `components`, `containers`, `views`, and `layouts`.

```
.
├── ...
├── src                      # Application source code
│   ├── components           # Generic React Components (generally Dumb components)
│   ├── containers           # Components that provide context (e.g. Redux Provider)
│   ├── layouts              # Components that dictate major page structure
│   ├── ...
│   ├── views                # Components that live at a route
│   └── ...
```

I think I understand the purpose and thought process of `components`, `containers`, and `layouts`.  But I'd like to hear your thought process and further details about the **`views`** folder.  This is the only React starter kit repo that I've seen that uses this approach.  So here are some questions:

1. What are the primary **benefits** and **drawbacks** of separating the `view` components from the other `container` components?

2. What about **nested routes** or **deep linking**?  Should *any* component that is specified in a `<Route />` go in `views`?  For example, say we have a page that has a tab control and we want to provide the ability for the user to copy/paste a URL which will not only open that page, but also open a particular tab on that page.  If we have a component for the "body" of the tab, should that component go in `views`?

Thanks!

**Comment by davezuko** [comment]
Hah, my "excellent" docs need a bit of an update, but thank you :P. As a preface, this is just _my own pattern_, it's how the starter kit comes out of the box because I like it, but you are not at all required to abide by it.

1)
**Drawbacks**
* Views are coupled to a specific Redux container (read: not very reusable). You can still export an unconnected version (just like in components), but it's a bit less intuitive. Views to me represent **top-level** routes (partially answering **#2**) in that it doesn't make sense to have a `view` for a route nested 4 levels deep. To me that should just be a component.

**Benefits**
* Easy to local in the project and often provides a 1:1 mapping against routes.
* You don't have to create both a container and a component file, it's assumed that a `view` is a connected component.

You could very easily just create `components` and then `containers` for those components to act as `views`. However, I really like `views` as it's very easy to get into the app and understand where the components live for routes, rather than muddying the components directory. It boils down to a clarity issue; yes, views are technically just containers around components, but a component (to me) implies a small component that is re-used very often; that is not the case with views.

#2) No, and this is maybe where it gets unclear. I would just create components (maybe w/ containers) for those.

The team I work on currently debated these conventions just the same as you when I started and transitioning us to redux, and we've kept with the `views` structure for now without any issues. I'd say pick whatever's more intuitive to you, if you want to be more pure about it `containers` and `components` alone might make sense.

**Comment by jasonkylefrank** [comment]
@davezuko Great, thanks for your explanations!
