### ISSUE TITLE
Webpack config to load LESS files

### ISSUE THREAD

**Issue by oleole90** [davezuko/react-redux-starter-kit#492]
There are some awesome react [widgets](https://jquense.github.io/react-widgets/docs/#/dropdownlist) out there that uses LESS. Since this starter kit isn't (yet) configured to load LESS files, we will miss out a lot of those widgets. Can't you please add the loaders for LESS files too? Or at least provide a quick snippet for that.

**Comment by davezuko** [comment]
From http://jquense.github.io/react-widgets/docs/#/getting-started, it looks like you just need to add the loaders specified in the setup instructions.

In: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L199-L207, add:

```js
[
  { test: /\.less$/, loader: "style-loader!css-loader!less-loader" },
  { test: /\.gif$/, loader: "url-loader?mimetype=image/png" },
]
```

We already have the css and font loaders, so you should only have to add the gif and less ones. The less loader isn't something I'm going to include in the base repo since it doesn't actually accomplish anything out of the box for new installs, so just let me know if you have any issues with getting it running after adding the above ^^.

**Comment by oleole90** [comment]
Thanks!
Worked like a charm!
Just discovered that [the plugin's doc](https://jquense.github.io/react-widgets/docs/#/getting-started) suggests the following **but your 2 lines works too**. 👍
```javascript
loaders: [
  { test: /\.css$/,  loader: "style-loader!css-loader" },
  { test: /\.less$/, loader: "style-loader!css-loader!less-loader" },
  { test: /\.gif$/, loader: "url-loader?mimetype=image/png" },
  { test: /\.woff(2)?(\?v=[0-9].[0-9].[0-9])?$/, loader: "url-loader?mimetype=application/font-woff" },
  { test: /\.(ttf|eot|svg)(\?v=[0-9].[0-9].[0-9])?$/, loader: "file-loader?name=[name].[ext]" },
]
```

**Comment by davezuko** [comment]
Great!
