### ISSUE TITLE
No 'params' in state.router

### ISSUE THREAD

**Issue by gaborluk** [davezuko/react-redux-starter-kit#540]
It is my understanding that [these properties](https://github.com/rackt/react-router/blob/latest/docs/Glossary.md#routerstate) should be present in `state.router`. However, the only property that's there is `location`.

This is what my `<Route />` looks like:
```javascript
<Route path='/whatevs/:param' component={WhatevsView} />
```

And my view:
```javascript
const mapStateToProps = function (state) {
  return {
    router: state.router
  }
}

// ...

console.log(this.props.router) // Object {location: Object}
```

I'm not sure if it's an issue with the starter kit, an issue with `react-router`, or I'm simply doing something wrong. Any help would be greatly appreciated.

**Comment by davezuko** [comment]
So `react-router-redux` only stores the `location` object (refer to the last bullet point in these release notes: https://github.com/rackt/react-router-redux/blob/master/CHANGELOG.md#202). I'm sure there's a good reason for this, but I'm just not aware of it.

That aside, if you need to access the params from `@connect`, `mapStateToProps` receives a second argument `ownProps`, which are the props passed to the component. In this case, since this component lives at a route you have full access to `ownProps.params.<whatever>`. Hope that helps.

**Comment by gaborluk** [comment]
Thanks for the help, @davezuko, and for, y'know, making my life infinitely easier to begin with. This does solve my problem.

**Comment by davezuko** [comment]
:tada:
