### ISSUE TITLE
Question: What is the recommended pattern for accessing application state from within a route's onEnter?

### ISSUE THREAD

**Issue by gaborluk** [davezuko/react-redux-starter-kit#542]
Title says it all, just looking for best practices and possible caveats.

**Comment by davezuko** [comment]
Hey, you can check out this issue here: https://github.com/davezuko/react-redux-starter-kit/issues/515, it talks about the same thing. In case you're on an old version of the repo, you can reference https://github.com/davezuko/react-redux-starter-kit/commit/cc0f7889577c1aea6ab13460296c4f8118d6910d for the necessary changes. With that, you have full access to the store in your route definitions, so you can make full use of [its API](https://github.com/rackt/redux/blob/master/docs/api/Store.md).

**Comment by gaborluk** [comment]
Thank you once again for a well-rounded answer, @davezuko.

**Comment by davezuko** [comment]
Happy to help!
