### ISSUE TITLE
Cannot resolve 'file' or 'directory' babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js

### ISSUE THREAD

**Issue by jaydenlin** [davezuko/react-redux-starter-kit#544]
Hi, I really like this starter kit. It's pretty neat!
However, I've got an issue when running `npm run compile`.
The error message is
```
Cannot resolve 'file' or 'directory' babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js
```
Could you help find out the cause ? Thank you.
My node version is v5.2.0

**Comment by davezuko** [comment]
Yeah I started having this same issue and just dropped the preset because I couldn't figure out why the dependencies weren't being installed in the correct location. See https://github.com/davezuko/react-redux-starter-kit/commit/fa604c3d8b1fd28175a4508913d34b462aef2484 for the necessary changes (or you can just install the dependencies yourself, but this is probably more maintainable).

**Comment by jaydenlin** [comment]
okay. Thank you!
