### ISSUE TITLE
Where does initialState come from?

### ISSUE THREAD

**Issue by mbrochh** [davezuko/react-redux-starter-kit#57]
I stared at this for quite a while now but I can't figure out two things:

1. Where does the initialState come from? I can see in that server render-routes middleware that the compiled server entrypoint is called via `yield runRouter` but only location is passed in. In the server entry point I can see that Router.run is called and has a function as a parameter that takes initialState but how does thisnvariable ever get set to anything?

2. All other starter-kits that I found do something like de-hydrating and re-hydrating the initialState by dumping the state that was used by the server as a variable into the global document scope so that the client render can pick it up again. Why is this not necessary in this starter-kit?

Bonus question: Usually my routes would need to fetch data from APIs onEnter, how would I do this here so that it still works with server sode rendering (needs to wait until everything is fetched).

**Comment by davezuko** [comment]
Hey, you're right - there is no way to provide initial state like this at the moment. It's something I've been meaning to get around to but just haven't; the server implementation could use quite a bit of love. So it's not that it's not necessary in this starter kit for some reason, I just haven't done it yet.

Sorry for the inconvenience; I'll make this a bigger priority and try to take a look at it early next week and see what can be done.

**Comment by mbrochh** [comment]
Thanks for the quick answer! Good to know that I'm not totally stupid ;)

Your starter kit is awesome, I really like how it is structured. If you ever get around that de/re-hydration problem, I think this would be one of the best starter kits around.

**Comment by davezuko** [comment]
Hey @mbrochh, I added the ability to inject initial state; it's currently on the master branch: https://github.com/davezuko/react-redux-starter-kit/blob/master/server/index.js#L25-L32. There's still some improvements I'd like to make to it, but one of the things holding me up is the current structure of the app, where the server doesn't have direct access to the source code (it just consumes some convenience methods compiled from `~/client/entry-points/server`).

Given this setup, I'm not sure how to go about solving your bonus question (in fact I've never even done this, so it's entirely new to me). I'll try to check out some other universal apps and see how they solve the issue, but this server configuration was intentional. In fact, one of the reasons I even built this starter kit was because I wanted to be able to use more of what Webpack has to offer (sass imports, for example), which is something that a lot of boilerplates just avoid altogether. So far the easiest solution is to just join that group and refactor the starter kit to only allow JS imports, but I'm not yet convinced it has to come to that, even though a better solution eludes me.

**Comment by davezuko** [comment]
Deferring to https://github.com/davezuko/react-redux-starter-kit/issues/71.
