### ISSUE TITLE
Different asset path in development and production 

### ISSUE THREAD

**Issue by madshargreave** [davezuko/react-redux-starter-kit#580]
Hi

Inside my `src/static` folder I have an `sounds` folder which I store mp3 files in to invoke from my Javascript as

```
import notificationSound from 'static/sounds/sound1.mp3'
```

This correctly gets bundled into my dist folder, but in production, the code still looks for 

```
static/sounds/sound1.mp3
```
even though it is located at `/sounds/sound1.mp3 (served from root)`, which fails

Any suggestions?

**Comment by davezuko** [comment]
Files in `static` are not meant to be compiled with webpack (I may have failed on the documentation here). If you _do_ wish to reference files in there, such as images that you don't want webpack to process, you can just reference them _without_ the `static` directory (e.g. `<img src='images/foo.png'` where the real path is `static/images/foo.png`). This is because, in development, the Koa server just serves those files as if they were at the root of your application, and after compilation those files are all just copied to the root of the dist folder. Think of it as though those files live outside of `src` (maybe I should move them...).

If you want a generic folder to house images or other assets, I suggest creating an `assets` directory and importing from there, since that folder (or any other) doesn't have any special logic to it.

**Comment by madshargreave** [comment]
I tried creating an assets folder and importing the sounds from there, but this results in the whole folder path being copied to the dist folder

```
dist/
  -- src
    -- assets
       -- sounds 
            sounds1.mp3
```

**Comment by thangngoc89** [comment]
Adjust your file-loader query. (?name=[path]....)

**Comment by davezuko** [comment]
Closing this since it's been inactive since @thangngoc89 's comment. Let me know if we need to reopen this, thanks!
