### ISSUE TITLE
routeActions are undefined

### ISSUE THREAD

**Issue by CreativeManix** [davezuko/react-redux-starter-kit#586]
[HomeView.js.txt](https://github.com/davezuko/react-redux-starter-kit/files/140546/HomeView.js.txt)

Not sure What I am doing mistake. I need to pragmatically change the route.

But it throws routeactions are undefined.

**Comment by davezuko** [comment]
We're on the `4.0.0` beta of `react-router-redux`, which does not appear to have `routeActions` any longer. Check https://github.com/reactjs/react-router-redux/tree/master#what-if-i-want-to-issue-navigation-events-via-redux-actions out and give that a shot :).

**Comment by davezuko** [comment]
Though note that you'll have to wire up the middleware as well until a PR is merged. See https://github.com/davezuko/react-redux-starter-kit/pull/569 for details.

**Comment by davezuko** [comment]
Just merged into master: https://github.com/davezuko/react-redux-starter-kit/commit/df356376a0d79cf00f9edc9e5d9047d3c641e727

**Comment by CreativeManix** [comment]
Thanks,

Sorry I am new to redux. May I know how can I access the store in component.

I am not getting in context nor on props.

**Comment by davezuko** [comment]
Closing since the issue has been resolved, but we can continue the discussion anyways.

You use `mapStateToProps` to apply a slice of the store to your component. See https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L59 -- here we take the `counter` state and insert it as an identically named property `counter` into our component. If you want to insert the _entire_ state of the store into your component, you could simply do:

```js
const mapStateToProps = (state) => ({
  state,
})
```

Now you'll have `this.props.state` which will be the entire state of the Redux store. Does that help?

**Comment by CreativeManix** [comment]
Thanks, I am able to access state. But it doesn't have dispatch method. Do I need to do anything specifically ?

**Comment by davezuko** [comment]
Same thing for `mapDispatchToProps`:

https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L62
```js
// second argument is `mapDispatchToProps`.
export default connect((mapStateToProps), {
  increment: () => increment(1),
  doubleAsync
})(HomeView)

// if you just want `this.props.dispatch`, you can either omit that argument _or_:
export default connect((mapStateToProps), (dispatch) => ({
  dispatch,
})(HomeView)
```

**Comment by davezuko** [comment]
See: https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by CreativeManix** [comment]
Thanks again. I understood now. I have updated HomeView.js as follows and able to change the route

const mapStateToProps = (state) => ({
  counter: state.counter
})

function mapDispatchToProps(dispatch) {
  return {
    increment,
    doubleAsync,
    dispatch,
  }
}

export default connect(mapStateToProps,mapDispatchToProps)(HomeView)


Hope this is the correct way to do it

**Comment by davezuko** [comment]
For `increment` and `doubleAsync`, you will need to use `bindActionCreators`:

```js
import { bindActionCreators } from 'redux'

const mapDispatchToProps = (dispatch) => ({
  dispatch,
  ..bindActionCreators({
    increment,
    doubleAsync,
  }, dispatch),
})
```

**Comment by CreativeManix** [comment]
Sorry when I do above I dont get dispatch in props.

**Comment by davezuko** [comment]
Can you post your code? That should work.

**Comment by CreativeManix** [comment]
[HomeView.js.txt](https://github.com/davezuko/react-redux-starter-kit/files/140992/HomeView.js.txt)

Error is 

Module build failed: SyntaxError: D:/RND/react-redux-starter-kit/src/views/HomeView/HomeView.js: Unexpected token (73:2)
  71 | const mapDispatchToProps = (dispatch) => ({
  72 |   dispatch,
> 73 |   ..bindActionCreators({
     |   ^
  74 |     increment,
  75 |     doubleAsync,
  76 |   }, dispatch)


It shows syntax error on two dots... If I remove it shows error in last line... I am doing some silly mistake but couldn't figure it out

**Comment by davezuko** [comment]
Needs to be 3 dots, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator :).

**Comment by CreativeManix** [comment]
ah... Thanks, I am new to JS development....

Really hard to work without VisualStudio :)

Everything ok now :), Thanks again for your kindly help

**Comment by davezuko** [comment]
:tada:

**Comment by learntoswim** [comment]
This thread really helped me a lot, mainly this snippet. Helps a lot for the newbie to React and Redux:

```
// second argument is `mapDispatchToProps`.
export default connect((mapStateToProps), {
  increment: () => increment(1),
  doubleAsync
})(HomeView)

// if you just want `this.props.dispatch`, you can either omit that argument _or_:
export default connect((mapStateToProps), (dispatch) => ({
  dispatch,
})(HomeView)
```

I'm enjoying using your starter kit, thanks for all the work you've put in!

**Comment by davezuko** [comment]
@learntoswim if you don't want anything from state and just want `this.props.dispatch`, it's as simple as:

```js
connect()(YourComponent)
```

**Comment by learntoswim** [comment]
@davezuko Appreciate the tip! Would you say that that approach is acceptable Redux / React architecture (any component having access to dispatch)?

**Comment by davezuko** [comment]
Not really, it's best to keep as few components connected as possible (generally) until it starts to become unwieldy, that way you have fewer places across your app that can actually produce changes. Also, any connected component will re-render when the store changes, so keep that in mind.

That's not to say it's completely wrong, but the objective of Redux is to minimize the surface area where things can change in your application, so avoid it where possible :).

**Comment by davezuko** [comment]
_just saw your edit, replied before that... one sec_

**Comment by davezuko** [comment]
So I don't know what `<SocialLoginFacebook />` is exactly; if it needs `dispatch` for some reason, then by all means pass it down. However, generally it would have a handler such as `onLoginSuccess` or `onLoginFailure` or something similar, which you would then provide your own handler to. In that handler (in the parent component) you could then dispatch whatever actions you wanted to, which keeps the app more flexible.

If every component starts dispatching actions, they become harder to drop into different parts of the application. Rather, you should strive to pass generic props in (think of an input's `onChange` or a Todo item's `onComplete`) that you can then handle however is appropriate at the time, rather than them being too smart about what to connect to and what actions to dispatch.

**Comment by learntoswim** [comment]
I appreciate your time and input.

In that example, `<SocialLoginFacebook />` has a callback that after the user logs in it passes the authenticated state to the store, essentially "unlocking" other components because the user has authorized.

Your comment makes a lot of sense. It's certainly too easy to get greedy and just bind dispatch everywhere. My concern was the continual need to pass dispatch around as a prop. I think the idea (which I've read a few times) of passing handlers to child (dumb) components from parent (smart) components is much easier to manage.
