### ISSUE TITLE
Why is the 'src' folder ignored in nodemon.js?

### ISSUE THREAD

**Issue by kevinchiu** [davezuko/react-redux-starter-kit#589]
See: https://github.com/davezuko/react-redux-starter-kit/blob/master/nodemon.json

**Comment by davezuko** [comment]
Because nodemon is only used to reboot the server, the client application (everything in side of `src`) is hot reloaded with webpack. The server uses webpack dev/hot middleware for live development, and this would not work if we kept rebooting the server. The reason we _do_ restart the server for changes in `server` is in case people are developing an API and want to see its changes reflected in real time, though I haven't tested this enough to know how well it works with the webpack middleware, per the initial comment.

**Comment by davezuko** [comment]
Closing for now, if you disagree with this (which could be totally valid, I might be ignoring something) feel free to let me know and I will reconsider.
