### ISSUE TITLE
Ctrl doesn't work 

### ISSUE THREAD

**Issue by wenqiW** [davezuko/react-redux-starter-kit#594]
Thanks for creating this project and it really helps. 

When I was trying to use Ctrl key in this website, I found that doesn't work. e.g., Ctrl+C, Ctrl+V. I don't think it is related with my computer or browser, as Ctrl works in other websites. Is there any way to fix it and make Ctrl work?

**Comment by davezuko** [comment]
My _only_ guess is that this is could be related to the devtools; can you confirm by commenting this line out and restarting the app? https://github.com/davezuko/react-redux-starter-kit/blob/master/src/containers/Root.js#L40.

If that doesn't resolve this issue (not convinced it will, since the dock monitor is smart enough to only prevent default if your key matches a control key) then I'm really not sure what else can be done, since there's literally nothing going on in this app in particular that would cause this.

**Comment by wenqiW** [comment]
Thanks - it works once devtools is commented. ;)
