### ISSUE TITLE
Can add some examples of Client - Server(api) Communication?

### ISSUE THREAD

**Issue by lukeqi** [davezuko/react-redux-starter-kit#608]
This project is very good, it is succinct and unopinionated, and it is very beneficial to me.

However, as a stater kit, why not add some examples ( could be simple ) to show how to make the client app communicate with the server api? I think it would be good for the starters to build a real web app based on this project.

As a newbie, I am searching for the tools that can send and get the data from the server. It will be better if this project provide some examples or suggest some solutions concerning the communication. 

Thanks!

**Comment by rkmax** [comment]
:+1: I agree this starter kit was my first contact with redux and react I think is awesome

**Comment by davezuko** [comment]
While I can see the benefit, it unfortunately goes against the aim of the starter kit. What makes this project useful is that it just gets boilerplate out of the way, it isn't an example project of how a feature complete React/Redux application might look. This, understandably, falls short for developers who are a bit more new to the stack and community, but it's a tradeoff I'm willing to make. I already have the impression that the starter kit is becoming unwieldy, and am aiming to remove rather than add.

That said, I get more and more requests every day to add more examples, so it might be beneficial to start a fork of this project that aims to demonstrate more real-world functionality. Furthermore, Ajax is not something that new to React nor Redux, so I'm not overly concerned with demoing it. I will think your request over in more depth tonight and figure out if it makes sense to add anything.

Thanks!

**Comment by Hnus-** [comment]
@davezuko Examples would be very nice. You once did branch showing me how to use `koa` as an api and it helped me **tremendously** to this day I am still using the concept it showed me in my project. It also made me to switch my backend to `koa` instead of `express` and I am very happy with it. 
Overall I could not be happier with this repo mainly thanks to its minimal approach but for newbs like me its sometimes hard to figure out where exactly things fit into this puzzle of libraries, middlewares etc. So some form of recipes or full examples would be awesome. 
If I can add one thing I would like to see is how to navigate between routes by dispatching actions I still didn't figure this one out. I think its because I didn't added middleware correctly but that is unrelated to this issue.

**Comment by chenfanggm** [comment]
@Hnus Here's how to nav thorough dispatching actions:
In "configureStore.js", add router middleware:
```
import { applyMiddleware, compose, createStore } from 'redux'
import { routerMiddleware } from 'react-router-redux'
import thunk from 'redux-thunk'
import rootReducer from './rootReducer'

export default function configureStore (initialState = {}, history) {

  const router = routerMiddleware(history)

  // Compose final middleware and use devtools in debug environment
  let middleware = applyMiddleware(thunk, router)
  if (__DEBUG__) {
    const devTools = window.devToolsExtension
      ? window.devToolsExtension()
      : require('containers/DevTools').default.instrument()
    middleware = compose(middleware, devTools)
  }

  // Create final store and subscribe router in debug env ie. for devtools
  const store = middleware(createStore)(rootReducer, initialState)

  if (module.hot) {
    module.hot.accept('./rootReducer', () => {
      const nextRootReducer = require('./rootReducer').default
      store.replaceReducer(nextRootReducer)
    })
  }

  return store
}
```

In your redux action:
```
import { routerActions } from 'react-router-redux'
export const logoutAndRedirect = () => {
  return (dispatch, state) => {
    dispatch(logout())
    dispatch(routerActions.push('/'))
  }
}
```

**Comment by davezuko** [comment]
Moving this to the suggestions for the `2.0.0` roadmap. Thank you for the suggestion, I'll open up another ticket if we decide to move forward with it.

**Comment by lukeqi** [comment]
Thanks a lot. @davezuko
