### ISSUE TITLE
Module build failed: Error: Cannot find module 'eslint-config-standard-jsx'

### ISSUE THREAD

**Issue by rkmax** [davezuko/react-redux-starter-kit#609]
I just clone, install dependencies and ran `npm run dev`. I'm using master 96bd1cd

**Comment by davezuko** [comment]
What version of npm2 are you on?

**Comment by scopendo** [comment]
I had this yesterday too. I was running whatever npm version came with node
v5.4.0. Problem went away after using nvm to install and switch to node
v5.7.0.

**Comment by rkmax** [comment]
@davezuko I have node 5.4.0 and npm 2.14.15

**Comment by davezuko** [comment]
@rkmax Unfortunately I've stopped trying to maintain both npm 2 and 3 due to severe differences in package resolution. If a fresh `npm install` does not solve the issue, then I'd chalk it up to npm2, in which case you will probably just have to bite the bullet and install it yourself. If you are willing and able to upgrade to npm3, and still experience the issue, I will gladly look into it further.

**Comment by rkmax** [comment]
Thanks @davezuko I'll give a try to npm3

**Comment by rkmax** [comment]
Yeah npm3 solve the issue. I just downgrade to npm2 because npm3 is slower than npm2 even with `npm set progress=false`
