### ISSUE TITLE
How would you get the server folder to compile as well?

### ISSUE THREAD

**Issue by kevinchiu** [davezuko/react-redux-starter-kit#625]
I understand that `npm run deploy` generates a `dist` folder that contains the `src` contents. How would you do the same thing for the server?

(I've used ES6/7 code for the server, but it's not deployable in that form.)

**Comment by davezuko** [comment]
You should not need to compile the server code, is there a reason in particular that you are trying to do so?

**Comment by kevinchiu** [comment]
Since I've used ES6/ES7 features in the code, node won't run it. For now, I've done this fix, which is not the greatest:

`require('babel-core/register')
var app = require('../bin/server.js')
`

**Comment by davezuko** [comment]
Right, that's totally valid, or you could just do `babel-node bin/server`, but you don't need to actually bundle the server to dist. The only reason the client code is bundled is because all dependencies need to be available in the web app and it has to run in non-ES6 compliant browsers, unlike your local node environment where you can freely run `babel-node` and allow dependencies to resolve at runtime normally.

**Comment by kevinchiu** [comment]
Unfortunately, babel-node (and the method I'm using as well) appear to be
highly discouraged for production.

http://stackoverflow.com/questions/30773756/is-it-okay-to-use-babel-node-in-production

**Comment by davezuko** [comment]
Gah it appears you are right, it's been so long since I did BE work.

**Comment by davezuko** [comment]
So looking at those issues they seem to detail what's needed; you don't need anything complex for the server since it does not have to be webpack'd in any way unless you're doing server-side rendering. If you wanted to avoid the build step you could fall back to writing ES6 code supported natively by your Node version, which could eliminate that pain point.

Thinking back to my last job and my current one, both BE teams are just transpiling on the fly (no compile step) and seem to be doing pretty well. Perhaps this not entirely the _correct_ way of doing it, but the apps have been small enough that they don't seem to be paying much of a price for it. I did also uncover https://github.com/babel/example-node-server which walks through the correct usage of babel on the server.

**Comment by davezuko** [comment]
There's also: https://medium.com/@Cuadraman/how-to-use-babel-for-production-5b95e7323c2f#.80q3j3ewt

**Comment by davezuko** [comment]
Closing since this is largely tangential to the starter kit and well documented elsewhere as seen above. Will consider improvements for the 2.0.0 release, though.
