### ISSUE TITLE
Can't import config

### ISSUE THREAD

**Issue by web2style** [davezuko/react-redux-starter-kit#644]
Here is my code `src/utils/check-url.js`:

```
import config from '../../config';
const {__PROD__} = config.globals;
const {compiler_public_path} = config;

export default function(url) {
  if (__PROD__) {
    return url;
  } else {
    var woUrl = url.replace(/(https?):\/\/[\.[a-zA-Z0-9\/\-]+/);
    return `${compiler_public_path}${woUrl}}`;
  }
}
```

I just want to strip out website url from a string in development mode.

But when running this code I get the following errors:

```
WARNING in ./~/yargs/lib/parser.js
Critical dependencies:
359:21-48 the request of a dependency is an expression
 @ ./~/yargs/lib/parser.js 359:21-48

ERROR in ./config/index.js
Module not found: Error: Cannot resolve module 'fs' in E:\pi-website\config
 @ ./config/index.js 11:10-23

ERROR in ./~/yargs/lib/completion.js
Module not found: Error: Cannot resolve module 'fs' in E:\pi-website\node_modules\yargs\lib
 @ ./~/yargs/lib/completion.js 1:9-22

ERROR in ./~/y18n/index.js
Module not found: Error: Cannot resolve module 'fs' in E:\pi-website\node_modules\y18n
 @ ./~/y18n/index.js 1:9-22

ERROR in ./~/os-locale/index.js
Module not found: Error: Cannot resolve module 'child_process' in E:\pi-website\node_modules\os-locale
 @ ./~/os-locale/index.js 2:19-43
```

This happens because of this exact line: `import config from '../../config';`. Can't understand why this works well in `build/webpack.config.js` line 5 `import config from '../config';` and doesn't work for me.

**Comment by davezuko** [comment]
The config is not meant to be imported in the app since it relies on dependencies/files that aren't meant to be bundled. I recommend either exposing additional globals as needed (you do not need to import the config to access `__PROD__`, for example, it's implicitly available on the "global" scope [technically inserted by webpack]) or creating your own custom config inside of `src` that's intended for the client bundle.

Closing since this is not in fact an issue with the project, but feel free to continue the discussion.

**Comment by web2style** [comment]
Ok, I see. Just `if (__DEV__)` works fine. But how can I access the `compiler_public_path` variable?

**Comment by web2style** [comment]
Thank you.

**Comment by JMacLulich** [comment]
Thanks @davezuko and @web2style I just posted the same issue.

But as I see my approach was flawed. 

Would be great if this was a FAQ Q&A or something as it appears as if it might be something that a newbie would stumble into. I'll close my other issue.
