### ISSUE TITLE
How to use arrow function and .bind() in component?

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#655]
I want to bind this to a react component, the code like this
savefile () {...}
<But type='ghost' onClick={this.savefile.bind(this)}>保存文件</But>
It says
69:38  error  JSX props should not use arrow functions  react/jsx-no-bind

And then I changed my code to
savefile (obj) {...}
<But type='ghost' onClick={() => this.savefile(this)}>保存文件</But>
The error warns this:
69:38  error  JSX props should not use .bind()  react/jsx-no-bind

Would you please tell me the way to bind this to function savefile() ? Thank you very much.

**Comment by davezuko** [comment]
That's just a lint error, see: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md -- it's suggesting that you don't create functions (arrow functions or via `.bind`) in your render method since every time the component renders they will be re-created (i.e. it is not performant).

There are three easy ways to avoid this:

## Option 1 - constructor

```js
class YourComponent extends React.Component {
  constructor (props, ctx) {
    super(props, ctx)

    // bind the method when your component is first instantiated
    this.saveFile = this.saveFile.bind(this)
  }
}
```

## Option 2 - arrow function method

```js
class YourComponent extends React.Component {
  // methods declared as an arrow function are autobound
  saveFile = () => {
  }
}
```

## Option 3 - autobind decorator

```js
import autobind from 'autobind-decorator'

class YourComponent extends React.Component {
  @autobind
  saveFile() {
  }
}
```

**Comment by WenXuanYuan** [comment]
@davezuko You solved my problem perfectly, Thank you!
