### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by dvlasenko96** [davezuko/react-redux-starter-kit#669]
Hello.
Firstly, thank you for this boilerplate. In my mind, it the best react starter pack. I want to use it for my work project, but can't. 
We need to server-side page prerendering for seo and socialshare.
I know, this question was earlier, and you answered this question, but i really need this.
Can you add the same optional functionality, or maybe anyone faced with this problem, and may to help me?
Thank you.

**Comment by davezuko** [comment]
I still don't want to go down the rabbit hole for this since it requires a fair amount of boilerplate and the feature requests constantly pile up. It also tends to make the boilerplate unwieldy or too opinionated, which has already been hard enough to avoid.

I really understand the need and am sorry that it doesn't come prepared out of the box, but I will be working on a recipe or some similar documentation.

**Comment by davezuko** [comment]
See: https://github.com/davezuko/react-redux-starter-kit/issues/212#issuecomment-165101373

**Comment by dvlasenko96** [comment]
@davezuko thank you for response.

**Comment by dvlasenko96** [comment]
If somebody want to cooperate for help each other to implement this feature, please connect with me.

**Comment by davezuko** [comment]
Will be commenting on this in FAQ/Wiki. Thanks.
