### ISSUE TITLE
Missing webpack-isomorphic-tools

### ISSUE THREAD

**Issue by hophacker** [davezuko/react-redux-starter-kit#674]
`webpack-isomorphic-tools` is missing in this repo, which is a must for a bleeding-edge web stack, from my point of view.

**Comment by davezuko** [comment]
I understand where you're coming from, but this debate over whether or not to include universal rendering has gone on since this project's inception. I will continue to keep it in mind, but at this point I'm sticking to my guns about keeping it client-side only (see https://github.com/davezuko/react-redux-starter-kit/issues/212#issuecomment-165101373).

**Comment by davezuko** [comment]
See also https://github.com/davezuko/react-redux-starter-kit/issues/669
