### ISSUE TITLE
Extend koa as my api?

### ISSUE THREAD

**Issue by chovy** [davezuko/react-redux-starter-kit#688]
Can you put a sentence or two about how to deploy this configuration?

I'd like to just extend the koa to start, but when I do `npm run deploy` all I get is client side code in `./dist`

How should I deploy the koa server to production?

If you aren't going to support server via koa in production, do you know of a modern koa 2.x starter kit you can recommend that works well for api and sockets?

**Comment by davezuko** [comment]
Take a look at https://github.com/davezuko/react-redux-starter-kit/issues/625#issuecomment-192299747 and the followup comments and see if that helps at all.

**Comment by davezuko** [comment]
Added a chore to improve (in this case, _start_) documentation for the production server workflow. Informal/internal todo list here: https://github.com/davezuko/react-redux-starter-kit/wiki/v2.0.0-Plans. Closing this since there's no immediate issue/action to be taken beyond some README/wiki updates. And just to clarify, we 100% support the server in production, but there isn't anything special to be done in the base starter kit since it's not necessary to compile it. If you run the server in production it will serve your compiled (production) app, but it's up to you to add more features.
