### ISSUE TITLE
how to use fs module inside the src folder?

### ISSUE THREAD

**Issue by jhlosin** [davezuko/react-redux-starter-kit#694]
I am trying to use fs module inside of the src folder and could not figure out how so far.
It keeps giving the error below. 

Module not found: Error: Cannot resolve module 'fs'

I tried to hack the webpack config file a bit after reading this article below with no luck.
http://jlongster.com/Backend-Apps-with-Webpack--Part-I#Getting-Started

Can anyone let me know how I can resolve/get around this issue?

**Comment by davezuko** [comment]
You can't use `fs` from `~/src` since the application is bundled for the browser which does not have access to a file system (let alone the requisite Node/C libraries required for `fs` to work). If you need to perform file system access, I suggest doing it in the `~/server` and exposing the functionality as part of your API.

**Comment by davezuko** [comment]
Note: it _is_ possible to ignore certain modules with webpack, allowing you to bundle server-side code wtih it, but that is not true for our application in `~/src` whose target is the browser. It all depends on your target environment.
