### ISSUE TITLE
css-modules @import from node_modules issue/question

### ISSUE THREAD

**Issue by chrisblossom** [davezuko/react-redux-starter-kit#701]
@davezuko, your repo was directly linked in https://github.com/css-modules/css-modules/pull/65.

I am trying to get css-modules to 
```js
// global.scss
:global {
  @import "~normalize.css/normalize.css"
}
```
results in:
```
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module '~normalize.css/normalize.css' in /Users/chris/github/app/src/components
```
[styles/core.scss](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/styles/core.scss) shows you are importing locally managed version. Did you have similar issues using the npm version?

This seems to be the suggested way to import css from node_modules. https://github.com/webpack/css-loader/issues/12 [SurviveJS's Webpack loading styles section](http://survivejs.com/webpack/loading-assets/loading-styles/)

@gajus I would love to see if you had any input on this as well.

Thank you for your time.

//cc @bebraw

**Comment by SohKai** [comment]
@chrisblossom Your problem is probably that you're specifying the `.css` extension ([see this PR for libsass](https://github.com/sass/libsass/pull/754). What if you drop it and just try to `@import "~normalize.css/normalize"`?

If that doesn't work, it might also be because you need a `modules` definition your webpack config's `resolve` option.

**Comment by davezuko** [comment]
Just shipped a change doing exactly what @SohKai recommends. Let me know if you run into any trouble.

Commit: https://github.com/davezuko/react-redux-starter-kit/commit/3dbdc0efeb8d03758d59db1732ff49cfdf3cbf28
