### ISSUE TITLE
Help with Redux structure in application

### ISSUE THREAD

**Issue by andyfaizan** [davezuko/react-redux-starter-kit#702]
Hi Dave,

I've started using your starter kit recently and have a couple of questions regarding the redux part. I am familiar with the conventional working of redux where one can access state via the store, dispatch actions and have reducers etc. Your starter kit is designed a bit differently, where one maps props to state etc. I guess this comes from the [react-router-redux](https://github.com/reactjs/react-router-redux) repo but I'm not quite sure. Can you please clarify how to work with the kit. As in, how do I access the store, create actions, dispatch them, subscribe etc. Is there a way to use the conventional redux functions with this kit?

PS: Sorry this is a nooby question, but I really liked your starter kit and wanted to use it for a project. Hope its not asking too much for you to explain.

Cheers,
Andy

**Comment by davezuko** [comment]
We are following the traditional redux/react-redux pattern almost exactly as it's described in tutorials and the API docs. We use the `connect` decorator to connect a component to the global store, selecting a slice of state from it by using `mapStateToProps`. See: https://github.com/davezuko/react-redux-starter-kit/blob/master/src/views/HomeView/HomeView.js#L59-L65.

There is not much more going on as far as redux is concerned; we wire up the store in `~/src/redux/configureStore` and provide it to the app in `~/src/containers/Root`, but all of that is standard to any redux app. You say you have experience with redux, so I'm a bit confused as to how to answer this in any more depth than what I just outlined. If there is something in particular that you would like clarification on and is specific to this starter kit, feel free to let me know and I'll do my best, but otherwise this sounds like it would be better suited to a generalized discussion forum.

Hope that helps.

**Comment by davezuko** [comment]
Hey @andyfaizan, let me know if you still need help with anything in particular. I'm going to close this since it is not an issue with the starter kit, but please don't hesitate to comment back if you're still having trouble. Personally, I've found our gitter channel to be super helpful with questions like yours, so you may also want to give that a shot.

**Comment by andyfaizan** [comment]
Hey Dave, its alright. I actually wasn't so familiar with redux when I started. I've gotten the hang of it now. Either way, thanks for the clarification. And well, I didn't know there was a gitter room for the project. Otherwise, I would've asked there. I do have something else to ask. Is there documentation somewhere that describes how to setup an editor for eslint? I was forced to add all src files to eslintignore because there are way too many warnings/errors reported whenever I run the code.
