### ISSUE TITLE
Debugging with VS code

### ISSUE THREAD

**Issue by GustavRitsch** [davezuko/react-redux-starter-kit#715]
Hello Visual Studio Code just released its 1.0 version and it is my main code editor for now. It features build in debugger which I would love to use for this starter kit mainly for `koa` server it would make things so much easier, no more `console.log` debugging or putting `debugger` statements inside code for client. I have no idea how should I set it up or if its even possible to debug the server. Does anybody have experience with this?
(If this question doesn't get any traction I'll close this to not pollute issues and ask on more appropriate places, maybe link here my findings)

**Comment by davezuko** [comment]
I use VSCode as well, so if you figure it out let me know ;). I'll see what I can find.

**Comment by davezuko** [comment]
It is possible to debug, but it looks like it takes more than a trivial amount of configuration to set it up. Check out https://code.visualstudio.com/Docs/editor/debugging for a pretty in-depth tutorial on it.

Since this is just a generic boilerplate I'm hesitant to make all the necessary changes, but if I can manage to get it working without adding a bunch of bloat for other users I'll consider it.

**Comment by davezuko** [comment]
From what I've found there isn't much that can be done that I'd like to integrate into the core package, since it's already getting a bit crufty. If you have found anything specific you think people would be interested in I'd be happy to add it to the readme or wiki, but I don't believe there's any additional action to be taken for now.
