### ISSUE TITLE
File size compile result

### ISSUE THREAD

**Issue by yansenarmandau** [davezuko/react-redux-starter-kit#723]
Hi,

i just compile this starter kit for fresh (no editing), but the result:
app.js => 100KB++
vendor.js => 90KB++

any one know, how to become 100KB of app bundle?
src folder is 50KB++

thanks

**Comment by davezuko** [comment]
`vendor.js` includes all of theses packages:

```js
    'history',
    'react',
    'react-redux',
    'react-router',
    'react-router-redux',
    'redux'
```

So that explains its size. As for `app.js`, that contains the babel-runtime, your transpiled code (which will be larger than your source code), and any other dependencies that didn't get selected for the vendor bundle. If you're compiling in dev, it will also include code for devtools and HMR. Compiling without `NODE_ENV === production` also means optimization plugins are not used, such as webpack's dedupe plugin, so the bundle sizes will be exaggerated.

All in all, if you run `NODE_ENV=production npm run compile` and take a look at what modules get placed in what bundle it should clear things up. If you find that there are optimizations we are missing please let me know and we can take care of them.
