### ISSUE TITLE
Have devTools off by default

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#728]
**Current Setting:**

_Root.js_
```
  render () {
    return (
      <Provider store={this.props.store}>
        <div style={{ height: '100%' }}>
          {this.content}
          {this.devTools} <-- This is ON by default
        </div>
      </Provider>
    )
  ```

Is there a way to set it OFF by default?

**Comment by davezuko** [comment]
Two ways:

1) If you just wish to _hide_ them, you can change `~/src/containers/DevTools`:

```js
  <DockMonitor
    toggleVisibilityKey='ctrl-h'
    changePositionKey='ctrl-q'
    defaultIsVisible={false}
  >
    <LogMonitor />
  </DockMonitor>
```

This will require you to use the toggle visibility key in order to show it.

2) Use `npm run dev:no-debug`. This will disable them completely. See: https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L79

Hope that helps!
