### ISSUE TITLE
Question: How should a view look like?

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#741]
I really like the architecture that this kit provides, but I am confused what should go into a view.
I render a `View` for every route, and `view` has become a combination of a `container` and a `component`.

```
export class PostIndex extends React.Component {
  props: Props;

  render () {
    return (
      <div className="post-index container-fluid">
        <div className="row post-index__row">
          <div className="col-sm-12">
            {postItems}
          </div>
        </div>
      </div>
    )
  }
}

const mapStateToProps = (state) => ({
  posts: state.posts,
})

export default connect((mapStateToProps), {
  fetchPosts
})(PostIndex);
```

It kind of ended up looking like a combination of a component and a container, which I am advised against doing. I think it'd make more sense if I didn't connect a `view` to redux `store`, and I used a view as a container for both components and containers.

How do you usually use views?

**Comment by davezuko** [comment]
Does this help at all? https://github.com/davezuko/react-redux-starter-kit/tree/v2.0.0#components-vs-views-vs-layouts.

On smaller projects I use views as a mix of a container and component, since it's highly unlikely that it will be reused. If your project isn't going to get beyond a couple of views, I think this approach works totally fine. On bigger projects, as @justingreenberg has pointed out and argued with his latest PR, you _should_ separate the two, where a "view" (component that lives at a route) is a dumb component wrapped in a container. There are some good docs to check out here: https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/containers/CounterContainer.js.

**Comment by davezuko** [comment]
Let me know if you have any other questions. The gitter channel is also a great place for questions like this!
