### ISSUE TITLE
React-transform-webpack-hmr issue

### ISSUE THREAD

**Issue by SACRD** [davezuko/react-redux-starter-kit#75]
Hot reload doesn't work again.

**Comment by bulby97** [comment]
Beat me to it :).

:+1:

**Comment by davezuko** [comment]
Sorry about that, let me check it out. I try to make sure I test everything before it's pushed but obviously not well enough. Might need to figure out some way of running tests for this.

**Comment by davezuko** [comment]
@SACRD @bulby97 I just pushed a hotfix to master to fix this by including `history` (which is a recent addition required by react-router) in vendor dependencies. I've opened up https://github.com/davezuko/react-redux-starter-kit/issues/77 to investigate better solutions to problems resulting from the vendor bundle, so hopefully a more robust solution can be found.

**Comment by SACRD** [comment]
@davezuko hotfix works fine (in dev and dev:debug)! Thank you very much!

**Comment by davezuko** [comment]
Awesome, glad that fixed it :). I'll close this for now and will try to test HMR more thoroughly in future updates.

**Comment by bulby97** [comment]
@davezuko thank you ! Do you plan to add react-transform-catch-errors ?

**Comment by davezuko** [comment]
@bulby97 I toyed with the idea for a while and couldn't really decide, mainly because I haven't used it yet (though it does look really cool). It seems like it would be worthwhile, so I'll check it out later; I don't have any real argument against integrating it.

Also, on a somewhat unrelated note @bulby97 and @SACRD , do you find yourselves using `dev` or `dev:debug` more often? I'm curious if the `:debug` distinction is even necessary, or if they should be flipped (default enables debugging, with an option to disable it). I don't think it's a problem right now, but I think `dev` should fit whatever the primary use case is.

**Comment by bulby97** [comment]
In my opinion, it's kinda verbose to use dev:debug, and I use more often dev:debug. I recommand to use redux dev tools as default debugging, and wait for this PR https://github.com/gaearon/redux-devtools/pull/107 :)

**Comment by SACRD** [comment]
@davezuko i'm using dev:debug more often because of state re-evaluating.

**Comment by bulby97** [comment]
@davezuko Actually it's possible to use ctrl+h to hide redux devtools https://github.com/gaearon/redux-devtools/pull/12

**Comment by davezuko** [comment]
@bulby97 yeah you can, but you also need to enable the devtools middleware for the store which people may not always want to do. I have a branch going right now to flip `dev` and `dev:debug`.

**Comment by davezuko** [comment]
@SACRD @bulby97 `dev` now enables devtools by default, but can be overriden with `dev:no-debug` if you want. https://github.com/davezuko/react-redux-starter-kit/pull/82
