### ISSUE TITLE
README Rewrite

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#765]
The readme had a lot of outdated information and was becoming fairly schizophrenic, so in an effort to force myself to clean it up I just started and committed the beginnings of a rewrite. I need to go back in and add documentation about redux-cli ( /cc @SpencerCDixon , just letting you know it's only temporary, needs to coincide with blueprint fixes) and pull as much else as possible into wiki pages (/cc @justingreenberg ).

## Todo
* [ ] redux-cli
* [ ] https://github.com/davezuko/react-redux-starter-kit/issues/730

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure /cc @justingreenberg -- highlighted it in README but can probably do an even better job of it.

**Comment by SpencerCDixon** [comment]
Sounds good, finally back from job orientation/traveling.  Let me know if you'd like me to do

**Comment by davezuko** [comment]
Nice, congrats and welcome back @SpencerCDixon .

**Comment by SpencerCDixon** [comment]
Thanks!  Really sorry for being super MIA, crazy couple of weeks to say the least.  Going to create a new project with the Fractal Structure so I can get up to speed and be able to contribute.

**Comment by davezuko** [comment]
Todo: https://github.com/davezuko/react-redux-starter-kit/issues/763

**Comment by gkedge** [comment]
The [Deployment Section](https://github.com/davezuko/react-redux-starter-kit#deployment) of your README wisely steers clear of enterprise/production/youknowwhatImsayin servers, an area that would be very difficult for you to maintain.  However, we recently had a developer start out with your kit creating all of his work leveraging Koa with port 80 open on his box to demo.  Prior to doing what it takes to deploy on one of our *real* servers, he departed.

Since it turned out to be a challenge understand putting a server into *'HTML5 mode'*, much more to set up a nginx, Apache, etc. server into HTML5 mode, I was wondering if adding a reference to react-router's [Configure Your Server ](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#configuring-your-server) section or a reference to a [document that I gather information on the subject](https://gkedge.gitbooks.io/react-router-in-the-real/content/) might be helpful to those starting out with your kit.

**Comment by davezuko** [comment]
@gkedge Woah, this got lost in the depths of the _second issues page_. That "Configure Your Server" post would definitely be helpful, so I will definitely do that.

**Comment by davezuko** [comment]
This has been added, and I'll link to your post in the FAQ.

**Comment by jeregrine** [comment]
@davezuko the immutable.js guide got missed in this task.
