### ISSUE TITLE
Correct way to use/import images into components .scss file

### ISSUE THREAD

**Issue by IljaDaderko** [davezuko/react-redux-starter-kit#782]
So I have a footer component that has following structure

```
src/
  components/
    Footer/
      index.js
      assets/
        myImage.png
      Footer.scss
```

inside my Footer.scss I'm trying to use myImage.png as background for my component so:
```

.Footer {
  background-image: url('./assets/myImage.png'); 
}
```

But this results in following error `Module not found: Error: Cannot resolve module 'myImage.png'`

**Comment by davezuko** [comment]
Is it really throwing a compile time error? If so, you can probably ignore most of what I'm going to say. What I'd figure would be happening is that your styles get loaded, the `.Footer` class attempts to load `./assets/myImage.png`, but that request is actually going to `localhost:3000/assets/myImage.png` which does not exist.

If you're following the fractal structure, you'll need to put images referenced in your styles in the root `~/static` directory (e.g. `~/static/images/myImage.png` and then reference it as `/images/myImage.png`). This is because in our current setup webpack does not process these images at all, as far as I am aware. Your other alternative is to keep it where it is an import it via your JavaScript, which will allow webpack to process it with a loader and bundle it accordingly.
