### ISSUE TITLE
[question] How do you run a compiled version?

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#783]
Is there a way to serve files that are in `dist/` folder in a local environment?

It says `Uncaught TypeError: Cannot read property 'router' of null` in my production environment and I'd like to debug what's causing this

**Comment by davezuko** [comment]
Could you detail what it is you're doing right now to serve your dist folder? If, for example, you run `NODE_ENV=production npm start` you should be able to see your working app at `localhost:3000` (in production the server will just serve your `/dist` directory, ignore the warnings about production readiness, they need to be written more clearly). If _that_ isn't working then there is indeed a problem.

**Comment by woniesong92** [comment]
That is definitely working. Another question: is there a way to deploy an uncompiled version of the app?

**Comment by davezuko** [comment]
That doesn't really make sense, since the whole objective of the build system is to make the application runnable in the browser. You _can_ run it with just node by `require`'ing the files locally, but that's the territory of universal rendering and this starter kit is not setup for that by default.

**Comment by woniesong92** [comment]
Thank you as always!
