### ISSUE TITLE
Cannot find the `interfaces` folder documented in README

### ISSUE THREAD

**Issue by hoodwink73** [davezuko/react-redux-starter-kit#790]
Hello guys

Thanks for putting this together.

I was going through the Zen example from the blog. There is an interface definition `Action` which was used without being imported from anywhere?

Then I wanted to check the `interfaces` folder in the root directory. And it was missing. Any new development on this? What am I missing?

**Comment by davezuko** [comment]
So, just as a heads up (this first paragraph doesn't answer your question, just some background), Flow has been removed since then in order to slim down the project. I still _highly_ recommend using it or TypeScript, it just wasn't necessary for the project. If you're not already doing so, you can use this tag: https://github.com/davezuko/react-redux-starter-kit/tree/v3.0.0-alpha.0 to get an environment that more closely (if not exactly) resembles that example you mentioned. 

_That said_, the `Action` interface was being included from the `flow-interfaces` package. See: https://github.com/TechnologyAdvice/flow-interfaces/blob/master/interfaces/action.d.js. This package is unmaintained since the Flow folks are working on an official solution, so use it at your own risk. You can see the interfaces repo being referenced here: https://github.com/davezuko/react-redux-starter-kit/blob/v3.0.0-alpha.0/.flowconfig#L16.

@mklinga you may want to link specifically to that tag in your post ^^ if you haven't already. Closing for now unless you have additional questions. Thanks!

**Comment by mklinga** [comment]
Thanks for the information, I updated the post.
