### ISSUE TITLE
node-sass compile time missing folder.

### ISSUE THREAD

**Issue by liamcoau** [davezuko/react-redux-starter-kit#791]
I'm not sure if there's somewhere you'd rather I put an error report, but I just did a fresh install and tried `npm start`. This is my console log for the start, I haven't touched any code, all dependencies seem to have installed fine (except FSevents), and localhost:3000/ just shows `Not Found`. I checked the node-sass folder, and there's no vendor folder, so it's no surprise it wasn't found...

```
colemanl@ubuntu:~/dev/cps$ npm start

> react-redux-starter-kit@3.0.0-alpha.0 start /home/colemanl/dev/cps
> better-npm-run start

running better-npm-run in /home/colemanl/dev/cps
Executing script: start

to be executed: babel-node bin/server 
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +42ms
  app:config Found overrides, applying to default configuration. +22ms
  app:webpack:config Create configuration. +3s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +23ms
  app:server:webpack-dev Enable webpack dev middleware. +742ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +146ms
  app:bin:server Server is now running at http://localhost:3000. +21ms
webpack built 2abd9dd14c8a3294cff9 in 10027ms
Hash: 2abd9dd14c8a3294cff9
Version: webpack 1.13.0
Time: 10027ms
                                Asset     Size  Chunks       Chunk Names
          app.2abd9dd14c8a3294cff9.js   718 kB       0       app
    1.counter.2abd9dd14c8a3294cff9.js  43.7 kB       1       counter
       vendor.2abd9dd14c8a3294cff9.js   382 kB       2       vendor
      app.2abd9dd14c8a3294cff9.js.map   850 kB       0       app
1.counter.2abd9dd14c8a3294cff9.js.map  54.4 kB       1       counter
   vendor.2abd9dd14c8a3294cff9.js.map   456 kB       2       vendor

ERROR in ENOENT: no such file or directory, scandir '/home/colemanl/dev/cps/node_modules/node-sass/vendor'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-284 13:2-17:4 14:20-290

ERROR in ENOENT: no such file or directory, scandir '/home/colemanl/dev/cps/node_modules/node-sass/vendor'
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275

ERROR in ENOENT: no such file or directory, scandir '/home/colemanl/dev/cps/node_modules/node-sass/vendor'
 @ ./src/routes/Home/components/HomeView.scss 4:14-291 13:2-17:4 14:20-297

ERROR in ENOENT: no such file or directory, scandir '/home/colemanl/dev/cps/node_modules/node-sass/vendor'
 @ ./src/components/Header/Header.scss 4:14-280 13:2-17:4 14:20-286

ERROR in ENOENT: no such file or directory, scandir '/home/colemanl/dev/cps/node_modules/node-sass/vendor'
 @ ./src/components/Counter/Counter.scss 4:14-281 13:2-17:4 14:20-287
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  546 kB       0       
webpack: bundle is now VALID.
```

**Comment by liamcoau** [comment]
I checked out previous commits and saw the recent node-sass upgrade, so I ran `npm install --save node-sass@3.3.3` and I think there are some dependency problems, but the `npm start` worked and I can see the web app now.

**Comment by davezuko** [comment]
Thanks for the report and the update. If I've read this right you say it's working now by upgrading `node-sass`, so I'm going to close this for now since all future users should be installing the required/fixed version as well.

Let me know if I'm wrong in this assumption, in which case we can reopen.

**Comment by liamcoau** [comment]
Sorry, I was trying to say that I fixed it by downgrading node-sass to
3.3.3. I looked at the commits and saw that it was recently changed from
3.3.3 to a newer version, and I undid that and now it works.

**Comment by davezuko** [comment]
Oh seriously? What's the latest version of `node-sass` that you tried and didn't work? At this point it might just be something that needs to be filed in their repo; I'm searching through their issues right now.

Sorry for misreading that!

**Comment by liamcoau** [comment]
Previously the requirement I had installed was ^3.7.0, I've only tried that
one and 3.3.3, so I'm not sure which version it actually breaks at. I'm
also not sure why this would just be affecting me either - I'm running a
really fresh install of Ubuntu 16.04 on my work computer that I just got
last week.

**Comment by liamcoau** [comment]
I also have this warning now since I downgraded:
`npm WARN sass-loader@3.2.0 requires a peer of node-sass@^3.4.2 but none was installed.`

**Comment by rechtar** [comment]
Thanks @liamcoau ! I encountered the same issue and got it (temporarily) fixed by downgrading `node-sass` to 3.3.3 too. Apparently they changed something which caused `includePaths` to be ignored.

**Comment by Rostbif** [comment]
i got this error too with the node-sass v3.7.0

**Comment by dustin-page** [comment]
Simlar problem with node-sass v3.7.0. I get the following error:
Error: ENOENT: no such file or directory, scandir 'C:\Working\my-app\node-sass\vendor'

In the package.json file it is looking for the "vendor" directory, which doesn't exist:

  "files": [
    "bin",
    "binding.gyp",
    "lib",
    "scripts",
    "src",
    "vendor"
  ],

Rolling back "node-sass" to "3.4.0" temporarily fixed the issue for me. However, I am now locked into this version.

**Comment by liamcoau** [comment]
Before I've had problems with a missing vendor directory in other packages,
and t required a `npm build` to generate system specific files.

**Comment by JMacLulich** [comment]
I've just encountered this same problem on Ubuntu 14.04.

I didn't have the problem when running the babel-node server under Mac OSX.

Is it just me or did other people have to add a tonne of dependencies to their `package.json` file to resolve all the module dependency problems? I might file a separate issue for this.

There is no `npm build` function.

Also now when I downgrade `node-sass` I get this:

`npm ERR! peerinvalid The package node-sass@3.3.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants node-sass@^3.4.2`

So the `sass-loader` is complaining because the version of node-sass is too old.

**Comment by r4j4h** [comment]
I ran into this and was able to get around it by removing the node-sass folder entirely from node_modules and asking npm to reinstall it.

**Comment by JMacLulich** [comment]
That's great, @r4j4h was that with the latest version of `node-sass`?

**Comment by Alex1990** [comment]
@JMacLulich I figured out this problem according to r4j4h's comment. And, the version of `node-sass` is `3.7.0`.

**Comment by JMacLulich** [comment]
@Alex1990 thanks, that helps alot, I can bump my version back up to `3.7.0` and rebuild the `node-sass` folder.

I found this command `npm rebuild node-sass` seemed to fix some of my issues.

**Comment by muhawo** [comment]
Figured out according to r4j4h's comment !

**Comment by r4j4h** [comment]
Sorry for not responding sooner, it was the latest version at time of my writing at least. Thank you @Alex1990  for filling in for me. Glad I could help! =)

**Comment by abdennour** [comment]
i have @3.8.0 i upgrade down to @3.4.0 And it works now.

**Comment by TimYi** [comment]
@3.10.1 also breaks.

**Comment by CNSKnight** [comment]
I did an `npm cache clear` && npm `install -g --save-deve node-sass`, and "we're back!".

**Comment by derjoker** [comment]
I don't know why, it works with @r4j4h's comment: after reinstall, the folder `vender` just shows up. It has nothing to do with node-sass version.

**Comment by fabiosantoscode** [comment]
Working around this by adding `mkdir -p node_modules/node-sass/vendor` to my prepublish script.

**Comment by crazyUI** [comment]
I am facing same issue with node-sass. If i do npm uninstall node-sass and npm install node-sass (or )
npm rebuild node-sass. Issue is resolved. But want to know how to avoid doing that. Why first time npm install is not installing node-sass correctly....

**Comment by mschipperheyn** [comment]
This also happens on Heroku from time to time. I found the only way to deal with this is randomly upgrading and downgrading to another version helps. But I hope this bug is eliminated soon

**Comment by tjwebb** [comment]
Also seeing this on Heroku

**Comment by zinkkrysty** [comment]
Had this issue today. Using `yarn`. 

I added a package (`yarn add moment`) that didn't change any other dependency. Suddenly `yarn start` didn't work (couldn't find node-sass/vendor). Removed `node-sass` from `node-modules`, then added the package since it clearly was a dependency: `yarn add node-sass` and ran `yarn start` without problems.

**Comment by weisd** [comment]
+1 
rm -rf node_modules/node-sass
yarn add node-sass

it works

**Comment by dapetcu21** [comment]
I have the same issue on Dokku. Shouldn't this issue be reopened?

**Comment by techhysahil** [comment]
Thanks @liamcoau, you saved lot of debugging time.

**Comment by qknight** [comment]
i have this issue with [yarn2nix](https://github.com/moretea/yarn2nix) and i filed [a bug](https://github.com/moretea/yarn2nix/issues/12#issuecomment-338763993) there.

question: why does `node-sass` rely on the rebuild and why can't it be installed properly otherwise? i tried a few different versions of node-sass and neither builds. i've also had a look at the source code but the `vendor` library is only mentioned like 10 times in the complete source. not sure how it gets populated and created at all.

also: should i report my issue upstream at `node-sass`?

probably related: https://github.com/sass/node-sass/issues/1812
