### ISSUE TITLE
Area to do server side api requests

### ISSUE THREAD

**Issue by Edmondton** [davezuko/react-redux-starter-kit#792]
Hello 
What is the recommendation on where to do server side api requests in this starter kit ?  
A short code example snippet would be great

Thanks.

**Comment by davezuko** [comment]
For smaller apps, you can just stick your async actions right along your synchronous action creators. For example, we do a _fake_ API request here: https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/modules/counter.js#L16-L33 (just using a setTimeout to simulate async). For bigger apps, the structure is up to you (I like to put them in their own `services` file, but that's just a personal preference).

I recommend reading http://redux.js.org/docs/advanced/AsyncActions.html and http://redux.js.org/docs/advanced/ExampleRedditAPI.html as it goes into more of the implementation details and recommended approaches.

Going to close this since it is not an issue with the starter kit. If you're still looking for advice I'd recommend trying StackOverflow, Reddit, or a board/chat meant specifically for discussions like this. Good luck!
