### ISSUE TITLE
Access store or state and actions from CoreLayout

### ISSUE THREAD

**Issue by sauravskumar99** [davezuko/react-redux-starter-kit#799]
I want to access store components from core layout so that i can send it to the child components upon page load...
```javascript

export const CoreLayout = ({ children }) => {
  console.log(children);
  //console.log(props);
  return (
  < div >
    < Header userName={userName} moreDataTo={sendHere} />
    < div className='container-fluid '>
      < div className={classes.mainContainer} >
        { children }
      < /div >
      < Footer/ >
    < / div >
  < / div >
)}
```
Consider this as a situation that when a user visits a page an ajax is fired which check the user logged in status and then updates the name in nav header or show Login button panel accordingly .... Thus I would be thankful if someone could give a solution for this situation...

**Comment by davezuko** [comment]
It's a component just like any other, so you can wrap it in a `connect` decorator. How you organize it is totally up to you (i.e. whether or not you put the `container` into its own file [e.g. `CoreLayout` and `CoreLayoutContainer` -- similar to the [counter example](https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/containers/CounterContainer.js))

```js
export const CoreLayout = ({ isAuthenticated }) => {
  return (
    // ...
    <Header showLogin={!isAuthenticated} />
    // ..
  )
}

export default connect((state) => ({
  isAuthenticated: state.session.isAuthenticated,
})(CoreLayout)
```

I'll leave this open for the remainder of the day just in case anybody else has something to add, but after that I'm going to close it since it's a question about redux usage and not this project in particular.

**Comment by sauravskumar99** [comment]
@davezuko I would like to get your opinion as to whether it would be better to add something like header to AppContainer or CoreLayout? Thank You

**Comment by davezuko** [comment]
Hey @sauravskumar99, if it were me I would probably put the responsibility in the component that renders the header, but it wouldn't be the end of the world to wrap the header component in its own container. I suggest if you have further implementation questions you post in our gitter channel (https://gitter.im/davezuko/react-redux-starter-kit) since that's a more appropriate place for general best practice questions.

Closing since there is no action to be taken from the starter kit.
