### ISSUE TITLE
Where has more example?

### ISSUE THREAD

**Issue by bodyno** [davezuko/react-redux-starter-kit#802]
I was wondering more code for the kit.
If has more example, please tell me.
Or I will close the issue.
Thanks

**Comment by davezuko** [comment]
We do not have a full application example, sorry. You might find https://suspicious.website/2016/04/29/starting-out-with-react-redux-starter-kit/ helpful, however. I also recommend checking out our gitter channel (in the readme) and asking around there since other users may be able to point you in the right direction.

Closing since there is no action to be taken in the starter kit. Good luck!
