### ISSUE TITLE
Questions: Steps to implement isomorphic rendering

### ISSUE THREAD

**Issue by Edmondton** [davezuko/react-redux-starter-kit#805]
Questions: Steps to implement isomorphic rendering

I see there is a comment in server/main.js to remove a few lines for isomorphic, but there would need to be some additional steps to populate initial state, and html markup.  Are you able to provide those steps.

**Comment by davezuko** [comment]
Sorry, no, and apologies if the comment in the server implied otherwise. This has been brought up numerous times and it's not something I'm willing to tackle in this project due to the amount of additional boilerplate/maintenance/etc. that would be required.

* https://github.com/davezuko/react-redux-starter-kit/issues/775
* https://github.com/davezuko/react-redux-starter-kit/pull/281
* https://github.com/davezuko/react-redux-starter-kit/issues/643
* https://github.com/davezuko/react-redux-starter-kit/issues/212#issuecomment-161355951

If you follow the docs for React/Redux/React-Router you can totally implement it yourself, the only thing you'll really have to deal with is whether or not to pre-process your server code with webpack (such as w/ its isomorphic tools) and then the consequences of that decision. Since this starter kit does not concern itself in any way with universal rendering, you may find more of your questions answered by checking out https://github.com/erikras/react-redux-universal-hot-example.

Good luck.

**Comment by Edmondton** [comment]
@davezuko - thanks for the response and for the links.  But it seems from the other links, a lot of people seem to be requesting the feature of isomorphic.  It does appear to be a legit request (from my perspective).  Just curious, is your starter kit only concerned with everything else except universal rendering / isomorphic ?

**Comment by davezuko** [comment]
It is a legitimate request, you're absolutely right, but those links are also just a small subset of many issues, opinions, and discussions that have accrued over the lifetime of this project, so they are not necessarily representative of the majority opinion. SPA's have for a long time worked perfectly without universal rendering, and though it is a great feature (i.e. for SEO) it's not a necessary part of "getting started" with React, Redux, et al. If you look at the number of issues (and types of issues) in the universal boilerplate, it's absolutely staggering, and I don't want the same to happen to this project.

The overarching theme for this project is that people should be easily able to take it and do whatever they want with it without having to completely rip it apart. _Basic_ universal rendering isn't super complex, but it becomes a slippery slope when you consider all of the other things that go along with it (how do I make API requests? Deploy the server? Handle images? Inject styles? Set page titles?). At that point, the decisions become incredibly personal and team- or needs-based, so drawing a line at an arbitrary set of a "supported" server features becomes difficult; as a result I took a step back and drew it simply at universal rendering.

Furthermore, universal rendering is something that I think you should only be doing when you really understand the foundation on which you're building, and that is in opposition to our goal, which is to give people who don't necessarily fully understand Webpack and this entire ecosystem an easy starting-off point that points them in the right direction where they hopefully won't shoot themselves in the foot. It's hard enough for me to keep up with issues as they stand now, with a lot of people treating this project as StackOverflow, so I really don't want to go down the road of adding even _more_ code that will raise questions.

So, ultimately, the rationale is multifaceted and has been thought about deeply over this project's lifetime, and it's not a decision made lightly. Hopefully that clears my position slightly.

**Comment by Edmondton** [comment]
@davezuko - I mean I get it.  It is definitely a tough and slippery slope for these requests.  Thanks for your time and response.

**Comment by janoist1** [comment]
If interested, check out [this](https://github.com/janoist1/universal-react-redux-starter-kit)
