### ISSUE TITLE
modular structure

### ISSUE THREAD

**Issue by kodermax** [davezuko/react-redux-starter-kit#814]
What is structure i should use, if I make modular application.
For example:
My application will contain 

- tasks

- calendar

- mail

**Comment by GustavRitsch** [comment]
Let assume you are now random internet citizen reading your question. Would you really get what are you asking about without any previous context or information? I believe it make sense in your head but sure does not in mine. Can you provide some additional information, what problems are you facing, maybe a bit of code then I am sure people will help you out. I recommend reading about fractal project structure it might be what are you looking for or look at older versions of this project which was then structured differently and pick between these two you can't go wrong

**Comment by davezuko** [comment]
Thanks for the response @GustavRitsch , I appreciate you jumping on this.

@kodermax the issues for this project is not the best place to post questions like this. I'm sure people would love to help, but you'll have better luck on StackOverflow or in our gitter channel (https://gitter.im/davezuko/react-redux-starter-kit). Closing since there is no action to be taken.
