### ISSUE TITLE
Minimize size of vendor bundle

### ISSUE THREAD

**Issue by aesteve** [davezuko/react-redux-starter-kit#823]
Hello, and sorry for opening an issue since it's just an open question and not a bug report. Please feel free to close this issue and point me at a Google Group or something if it's more relevant.

Thanks to your starter kit, I was able to split my application into a vendor / app bundle chunk which is great, but still, the vendor bundle size is very huge, because of the https://github.com/callemall/material-ui dependency. 

Even though I'm not importing the whole material-ui icons and stuff within my code, the bundle size doesn't change. I've taken a look at http://stackoverflow.com/questions/34239731/how-to-minimize-the-size-of-webpacks-bundle and thus changed my import syntax as mentionned in the first answer but still, the whole material-ui seems to be bundled into vendor.js.

Does any of you guys has a pointer, an example, a piece of webpack config file or doc I could read so that I can reduce the size of my vendor bundle ? Any help would be appreciated.

Thanks a lot for your work and the boilerplate, it helped me a lot.

**Comment by davezuko** [comment]
I believe what you need is something called _tree shaking_, which is one of the selling points of webpack 2.0. I'm hoping to migrate this project over to that version sooner rather than later, which should help you with your issue.

If you only want select pieces of the library, do not `material-ui` to your vendor bundle. Vendor dependencies are _always_ included in full, even if they are never imported. What you should do is import the direct paths of the components you want in your app; that way you will only import what you use, the only downside being that they will be put into your application bundle(s).

**Comment by aesteve** [comment]
Thanks a lot for your answer, I had read about webpack 2.0 and tree shaking but wasn't sure it was exactly what I was in need of.

Your solution is worth giving a try. The compromise will be all mine. 

Thanks again fir the crystal clear answer.
