### ISSUE TITLE
npm run deploy:prod fails

### ISSUE THREAD

**Issue by FutureKode** [davezuko/react-redux-starter-kit#825]
Seeing a not helpful bunch of errors when running `npm run deploy:prod`, see screenshot http://cl.ly/1u1J103o0Y1x

However, if I set `env : process.env.NODE_ENV || 'production',` in config/index and run `npm run deploy` then it builds fine :/

I have all the latest code from the starter kit 3.0.0-alpha.0

`npm run lint` shows no errors/warnings

[npm-debug.txt](https://github.com/davezuko/react-redux-starter-kit/files/281989/npm-debug.txt)

**Comment by FutureKode** [comment]
ok, my colleague said that when he ran '`npm run deploy:prod` manually in SSH' he got:

```javascript
ERROR in ./src/routes/Restaurant/components/ModifierModal/ModifierModal.js
Module build failed: TypeError: /home/forge/collectfood.in/react-redux/src/routes/Restaurant/components/ModifierModal/ModifierModal.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"

[3:02] 
ERROR in ./src/components/LoginModal/LoginModal.js
Module build failed: TypeError: /home/forge/collectfood.in/react-redux/src/components/LoginModal/LoginModal.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
```

Why can we not see these errors in development?

**Comment by davezuko** [comment]
It's because of https://github.com/thejameskyle/babel-react-optimize, which is only run in production. At this point I'm leaning toward removing it since it can cause hard-to-debug issues if you components are written in an unsupported way. If you remove it from here: https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L134 your app should compile just fine.

**Comment by FutureKode** [comment]
Ah I see. The errors were being caused by me using react-bootstrap like this:

```js
import { Modal } from 'react-bootstrap'
...
<Modal>
<Modal.Header>
```

when it should be:

```js
import { Modal, ModalHeader } from 'react-bootstrap'
...
<Modal>
<ModalHeader>
```

**Comment by davezuko** [comment]
Yup, that'd be it. If you can do the latter and keep the optimization plugin I recommend doing that, but if you want to save yourself any future headaches it's not the end of the world to drop it. It's a bit strange that you didn't see the babel errors during your initial report, though.

**Comment by AubreyHewes** [comment]
I was having the same problem (latest starterkit).. the `deploy:prod` was failing.. every other compile command worked.. 
Removing `react-optimize` is a solution; though the optimization _should not_ be ignored. So why is it failing...

I worked out that, in my case, it was due to; Hopefully this helps someone; Older versions of the sk (starter-kit) did not use `react-optimize` so my code was opinionated on previous sk: A `React.Component` exported as a redux connected component. This seems to be a breaking anti-pattern when enforcing `react-optimize`.

(what whaaat?) ;

#### Fail

````
import React from 'react';
import { connect } from 'react-redux';

// longhand
export class View extends React.Component {
  render () {
    return <div>FAIL on deploy:prod with react-optimize</div>;
  }
}

// export default redux connected component
export default connect()(View);

````

#### Works
##### is a separation of concerns (sic); redux-container/react-view

`View.js`;
````
import React from 'react';

// longhand
export default class View extends React.Component {
  render () {
    return <div>aight on deploy:prod</div>;
  }
}
````

`Container.js`

````
import View from './View';
import { connect } from 'react-redux';

export default connect()(View);

````

This works as the `React.Component` is the exported class, not a connected/wrapped class.. It seems to be down to `react-optimize` recognizing a `React.Component`. Though I could be wrong; atm I have no time to look into `react-optimize` any further ;-)


Possibly the [sk](https://github.com/davezuko/react-redux-starter-kit) needs to mention that this separation is now _explicitly_ required? (or did  I miss a beat?)

**Comment by brianzinn** [comment]
This is not an issue with the starter kit, but I wanted to add how I was able to fix another issue related to 'react-optimize'.

Some react-bootstrap components (ie: Navbar.Form) are not exported how @FutureKode was able to address this issue, since there is no NavbarForm export equivalent.  Not sure this is the best way, but I was able to keep production 'react-optimize' by directly importing (alias is optional):
`import {Form as NavbarForm} from 'react-bootstrap/lib/Navbar'`

`render() { <NavbarForm pullRight>{}</NavbarForm> }`

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Navbar.js
https://github.com/thejameskyle/babel-react-optimize/issues/19
