### ISSUE TITLE
Code Coverage not 100%

### ISSUE THREAD

**Issue by urbaitel** [davezuko/react-redux-starter-kit#829]
Is there a reason why code coverage is not 100% or was it simply not completed for the starter code?

**Comment by kolpav** [comment]
You can always submit PR if you feel something is missing or coverage could be higher.

**Comment by davezuko** [comment]
100% coverage for this project is really not all that important to me, and there are a few issues with the coverage reporting anyways, esp. now that isparta is apparently deprecated (I'm looking into this). It's more to just demo the test suite rather than test the project itself, if that makes sense.
