### ISSUE TITLE
Hot module replacement reloads entire hierarchy

### ISSUE THREAD

**Issue by aherriot** [davezuko/react-redux-starter-kit#833]
When I update a file in the component tree, I expected it to only update that one piece and its children, but instead the root component reloads (and everything else on the page). For example, if I change only the style in `src/routes/Home/components/HomeView.scss`, I see this in my console:

```
[HMR] bundle rebuilding
client.js?e526:126 [HMR] bundle rebuilt in 1477ms
process-update.js:27 [HMR] Checking for updates on the server...
bootstrap 78a2d30…:48 XHR finished loading: GET "http://172.28.128.1:3000/a11895716c62a5071276.hot-update.json".hotDownloadManifest @ bootstrap 78a2d30…:48hotCheck @ bootstrap 78a2d30…:267check @ process-update.js:64module.exports @ process-update.js:28processMessage @ client.js?e526:139handleMessage @ client.js?e526:65
process-update.js:100[HMR] Updated modules:
process-update.js:102[HMR]  - ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./src/routes/Home/components/HomeView.scss
process-update.js:102[HMR]  - ./src/routes/Home/components/HomeView.scss
process-update.js:102[HMR]  - ./src/routes/Home/components/HomeView.js
process-update.js:102[HMR]  - ./src/routes/Home/index.js
process-update.js:102[HMR]  - ./src/routes/index.js
process-update.js:107[HMR] App is up to date.
```

I have used other webpack setups where only the pieces that change are updated, and not their parents, but I can't determine what is different about this configuration. Is this a bug in the setup or expected behaviour? What can I do to get only components downstream to update?

**Comment by davezuko** [comment]
It's the expected behavior for now until we finish integration `v3` of react-hot-loader. The previous recommended implementation, using `react-transform` with `react-transform-hmr`, was deemed a less-than-desirable approach by the community and project maintainers, where they opted for more "vanilla" use of webpack HMR. If you want the type of hot reloading you mentioned, you can totally use this project's `v2` release since it still uses that workflow.

See: https://github.com/davezuko/react-redux-starter-kit/releases/tag/v2.0.0

**Comment by aherriot** [comment]
Thanks for the super fast reply and detailed answer!

**Comment by davezuko** [comment]
No problem, I just happened to check my email at the right time :). Hopefully we'll get this fixed sooner than later, I've just been pulled a bit away from the project for the past couple of weeks.
