### ISSUE TITLE
Question: Why use `__BASENAME__`?

### ISSUE THREAD

**Issue by jsfr** [davezuko/react-redux-starter-kit#846]
Currently we have `history` as an outright dependency in `package.json`. It cannot currently however be upgraded to  ^3.0.0 (which is the newest version) as react-router does not yet support this version.

Digging a bit I can see that the reason we have it as a dep is because we set a basename on the history in `main.js`.

What is the benefit to this? Would it not be better to simply use the `browserHistory` directly from react-router instead, and remove history?

**Comment by davezuko** [comment]
Probably, I did do a double take myself the other week after noticing this.

**Comment by davezuko** [comment]
I think I misinterpreted this when I first read it. We _do_ need to provide the ability to set a basename even though it's not used in the example application. Many users[1][2] host their applications under sub-routes, and it seems silly to not provide support for this out of the box.

That said, I _would_ love to eliminate the `history` dependency, but assuming I'm reading the `react-router` [docs](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#customize-your-history-further) correctly, it's necessary in order to provide a basename.

* [1] https://github.com/davezuko/react-redux-starter-kit/issues/852
* [2] https://github.com/davezuko/react-redux-starter-kit/issues/704
