### ISSUE TITLE
Entry-points files in separate folders

### ISSUE THREAD

**Issue by bulby97** [davezuko/react-redux-starter-kit#85]
It seems more logical to me to put 
- `client/entry-points/client.js` in `client/main.js`
- `client/entry-points/server.js` in `server/main.js`

What do you think ?

Btw, I made some folder restructuration (just for my own little project) because I prefer to work by modules/features, but this is purely opiniated. You can take a look [here](https://github.com/Kilix/react-redux-starter-kit) if you want.

I give you an example. 
For a todo feature we have : 
- todo.react.js (to differanciate with todo.js which is a model if necessary)
- todo.page.js (when in todo is a page in route handler)
- todo.js (model)
- todo.spec.js
- todo.scss
- reducer.js
- actions.js

Voilà.

**Comment by davezuko** [comment]
I can see the confusion with the server entry point being in `client`. It used to make more sense back when `client` was named `src`, which I think would be the best option should it be renamed. I'm not too keen on putting it in `server`, since it truly has nothing to do with the server, it's just the client application bundled in a way that the server can use it (this has to be done for non-js asset support).

As far as the internal structure, I'm probably going to leave it as is (in terms of feature vs. type), just because the starter kit is already fairly simple and people are free to make changes as it suits them, as you have done. I'm definitely open to reconsidering the name `client` in favor of `src`, however, if you want to provide your thoughts on that.

**Comment by bulby97** [comment]
+1

**Comment by davezuko** [comment]
Renamed in https://github.com/davezuko/react-redux-starter-kit/pull/86.
