### ISSUE TITLE
how to set basename to a dynamic URL

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#850]
We are using `1.0.0` of the starter kit and it works great, except when we are trying to host on our SAP system.

SAP hosts via the URL `http://sapd1.local/sap(==somerandomtoken)/bc/bsp/sap/zmanpower/index.html`

We have tried setting `__BASENAME__` but it doesn't work because as SAP injects the random token and the page won't load. Is there an "easy" way to turn off "html5mode" so we can use hash based URLs or a way to dynamically build the BASENAME from `window.location.pathname`

**Comment by davezuko** [comment]
You won't be able to use `__BASENAME__` since that is determined at compile time. You could, however, just ignore the global in production and pass it to `history`/`react-router` at run time based on, as you say, what you parse out of the window location. I don't really know what to add here that's specific to the starter kit, since this is more just a usage question for `react-router` and related libraries.

**Comment by mikedevita** [comment]
thanks. I ended up swapping browser history out for hash history it works now and will be fine for our use case.
