### ISSUE TITLE
Compiled files doesn't work

### ISSUE THREAD

**Issue by allanesquina** [davezuko/react-redux-starter-kit#852]
Hi, first of all, thanks for this project, is too useful.
I'm trying to build the app that I've made with this boilerplate, but after run `npm run compile`, nothing happens on the browser and no errors are displayed, only the css file is loaded and executed, the js files are loaded but doesn't start the app. I've tested with a pure clone of this repo and I've got the same result. Am I doing something wrong? 
I'm using node `6.2.1`, npm `3.9.3`.

I've put a sample here:
http://allanesquina.github.io/react-pomodoro/

Can you help me? Thanks guys.

**Comment by davezuko** [comment]
It's because your app is hosted under `/react-pomodoro` (so no routes are matched); you'll need to adjust the `__BASENAME__` accordingly in production. You can either edit this by modifying https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js or, if you noticed https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L87, you can do:

`BASENAME=react-pomodoro npm run compile` and see if that works.

**Comment by allanesquina** [comment]
Man, awesome, it works perfectly now.
Thank you very much for the fast feedback, I appreciate that.
:+1:

**Comment by frankbolviken** [comment]
Isn't there anything you could do to make this work dynamically from where you deployed.
As in, on this server I want it to be deployed under root/app and on another server I want it to be deployed on root ? My brain struggles with grasping the fact that I need to know compile-time where this is going to be deployed :(
