### ISSUE TITLE
Set BASENAME not working

### ISSUE THREAD

**Issue by nie-xin** [davezuko/react-redux-starter-kit#880]
I checked the solution of [#852](https://github.com/davezuko/react-redux-starter-kit/issues/852) which says we can deploy app to subfolder by setting the BASENAME. But that doesn't work for me, the passing BASENAME didn't change the src url script tag, they always point to /.

I also tried to change the compiler_public_path on environement.js. This time the first 2 chunks js and css were loaded, but not the rest. There is no console error and the page stays blank.

I would like to know the proper way to deploy the dist files to a subfolder like /sub. Any idea?

**Comment by nie-xin** [comment]
Thanks @davezuko for fast response :) I might figure it out. I will do more test to confirm my solution and will let you know asap.

**Comment by golgistudio** [comment]
Was having a similar problem - I need to publish to gh-pages, and also host on a wordpress site.  Needed to make two changes

1) Change compiler_public_path in config/environments.js for the production configuration to '' instead of '/' as @nie-xin did.
2) Change src/main.js to use createHashHistory instead of createBrowserHistory.   

I've published the prod build to gh-pages here
[](https://golgistudio.github.io/react-redux-starter-kit/#/?_k=17jpal )

Code change is here
[](https://github.com/davezuko/react-redux-starter-kit/compare/master...golgistudio:master)

createBrowserHistory vs createHashHistory description is here.  createBrowserHistory is preferable in most cases - react-router docs...
https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md

**Comment by nie-xin** [comment]
@golgistudio Thank you for your push. I found that we could do that a bit simpler: 

1. Change compiler_public_path to subfolder path, for example '/sub/'
2. Pass same BASENAME on npm compile, just like this: BASENAME='/sub/' npm run deploy:prod

And you shall get script route complied correctly that will work on subfolder.

@davezuko Since many people hosting app on sub folder, do you think it worths a few words on the doc?
