### ISSUE TITLE
What is the use of actions inside src/routes/Counter/modules/counter.js?

### ISSUE THREAD

**Issue by Sir4ur0n** [davezuko/react-redux-starter-kit#897]
More of a question really, but I just can't see the use of the `actions` const in `src/routes/Counter/modules/counter.js`.

I tried removing it and it still works.

Is it some forgotten fragment to delete? Or is there some hidden use I missed?

**Comment by devinivy** [comment]
I think you'll find that it's used by the tests.

**Comment by twelch** [comment]
I found that you don't need it if you are importing and mapping your actions individually to your components.  But if you have a lot of actions or they are changing a lot then it's handy to just import and map the actions object to your component.

`this.props.actions.myaction`
instead of
`this.props.myaction`

**Comment by Sir4ur0n** [comment]
My point was more, shouldn't we either use it in the business code (not just the tests) or remove it all together? A variable created only for tests in the business code looks weird to me.

**Comment by kolpav** [comment]
@Sir4ur0n This is how you define exports in ES6. You can then do something like this `import { increment } from 'modules/counter'` or in another file you might need both `import { increment, doubleAsync } from 'modules/counter'`
In this small project you will not see any other use case for this but for testing. But in larger projects it is very common to import actions from other modules a dispatching them.
