### ISSUE TITLE
How many libraries add to webpack compiler_vendor?

### ISSUE THREAD

**Issue by brunogarcia** [davezuko/react-redux-starter-kit#905]
Hi,

I have a question. We're working in a middle size app, so we're using a few libraries (more than twelve):
We think is really good idea to separate our code from third-party libraries.
Do you think is a good idea compile all those into vendor.js?

Thanks!

**Comment by belliAndrea** [comment]
i did the same, i've added most of the vendor i use in compiler_vendor,
now my vendor file size is 500kb and it will be usefull to use a bundle analyzer like [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer/blob/master/package.json), but i cannot manage to make it work with this starter. Can someone help?

**Comment by davezuko** [comment]
I only put the vendor dependencies that are global to the app in `vendor`. Anything else that could be split between smaller bundles is best kept there, so that the initial page load can be as small as possible. Ultimately this varies between teams and projects, so I can't provide a universal recommendation other than "package your app in such a way that repeat visits have to download as little repeated code as possible when the application changes".
