### ISSUE TITLE
vendor.js 3.9Mo size in dist/

### ISSUE THREAD

**Issue by bulby97** [davezuko/react-redux-starter-kit#92]
Is it normal ? Production vendor.js is heavier than developement vendor.js

**Comment by MrEfrem** [comment]
Change devtool to 'source-map' in webpack config. 
'inline-source-map' can is necessary in the development mode though I don't see a difference since debugging both in ff and in chrome works with 'source-map', but in production precisely there shall be 'source-map'.

**Comment by davezuko** [comment]
I'll have to check out why the production vendor bundle is larger than development, but the bundle itself will be pretty hefty, since it includes all of these:

```
[
  'history',
  'immutable',
  'react',
  'react-redux',
  'react-router',
  'redux',
  'redux-devtools',
  'redux-devtools/lib/react'
]
```

As well as babel-runtime, which I believe isn't unsubstantial. Immutable could be pulled out if you're not using it, and I'd like to remove redux-devtools but can't (to my knowledge) because of a conflict with `redux-devtools/lib/react` and `react`.

**Comment by gaearon** [comment]
>I'd like to remove redux-devtools but can't (to my knowledge) because of a naming conflict with redux-devtools/lib/react and react.

You can helps us by [separating LogMonitor into a separate project](https://github.com/gaearon/redux-devtools/issues/61). Then there'll be no `redux-devtools/lib/react`. :wink:

**Comment by davezuko** [comment]
@gaearon haha, now I can't decline. I'll try to get to it sometime next week :).

**Comment by bulby97** [comment]
@MrEfrem 309ko ! Awesome ! In fact it was inline sourcemap :). Separate sourcemap is 2.7 Mo :+1:

**Comment by davezuko** [comment]
@bulby97 Saw you post this just as I updated the master branch to use regular source-map. Thanks again to @MrEfrem. Closing this for now then.
