### ISSUE TITLE
Files in `src/styles` are not watched

### ISSUE THREAD

**Issue by jasongonzales23** [davezuko/react-redux-starter-kit#933]
This may be a misunderstanding of how to use this framework, but I have some reusable styles in `src/styles` (variables and such) that I import into component style modules. When I edit the files in `src/styles` webpack doesn't rebuild automagically. And for the life of me I cannot figure out how to config this--I promise I've RTFM and "heuristically" played with a lot of the config :) Any advice is appreciated!

That said, I see this is more than a support issue on my part potentially. This might be nice to document either in the code or the README.

**Comment by davezuko** [comment]
Last I checked, if you are using CSS modules you do not get the benefits of HMR, due to how they are compiled. The easiest solution is just to CSS modules off and everything should just work, but if you want to keep them you can also wrap your style imports in `module.accept` blocks, though this is painful to do everywhere. There may be some workarounds out for this, but I'm not familiar with them to point you in the right direction.

**Comment by jasongonzales23** [comment]
@davezuko thanks for the reply! But I am not sure what you mean by "The easiest solution is just to CSS modules off and everything should just work..." Could you give just a brief explanation?

Cheers!

**Comment by bhj** [comment]
@jasongonzales23 You may have found this already but I believe he's referring to https://github.com/davezuko/react-redux-starter-kit/blob/master/config/index.js#L35

**Comment by jasongonzales23** [comment]
@bhj thanks! I did notice that but had forgotten about this thread. Also, the @values feature is pretty well hidden in here. I wish I had known earlier that that is how you import.

**Comment by helloruli** [comment]
i have the same issue.

**Comment by davezuko** [comment]
Removing CSS modules so this will be a non-issue.
