### ISSUE TITLE
Suggestion for faster reducers:

### ISSUE THREAD

**Issue by bingomanatee** [davezuko/react-redux-starter-kit#934]
just have an identity reducer alternate for unfound reducers:
````
const echo = (state) => state;
export const chessReducer = (state = initialState, action) => (ACTION_HANDLERS[action.type] || echo)(state, action);
export default chessReducer;
````

**Comment by kolpav** [comment]
How is that faster?

**Comment by bingomanatee** [comment]
sorry; I should say, simpler.

**Comment by davezuko** [comment]
I understand what you've changed, but I'm not convinced that it's necessarily _better_, it's just different. If you compare it to the existing implementation: https://github.com/davezuko/react-redux-starter-kit/blob/master/src/routes/Counter/modules/counter.js#L40-L55:

```js
// ------------------------------------
// Action Handlers
// ------------------------------------
const ACTION_HANDLERS = {
  [COUNTER_INCREMENT]: (state, action) => state + action.payload
}

// ------------------------------------
// Reducer
// ------------------------------------
const initialState = 0
export default function counterReducer (state = initialState, action) {
  const handler = ACTION_HANDLERS[action.type]
  return handler ? handler(state, action) : state
}
```

Rather than defaulting to an identity function (your `echo`), we just return the state directly if no handler exists. This removes an unnecessary function call, though the performance difference is beyond negligible. I guess yours removes a variable assignment, but overall I think the clarity of the existing code is fine enough to not warrant a change.

Personally, I just use the following for creating reducers, which makes the above implementation detail irrelevant to the creation of individual reducers.

```js
const createReducer = (initialState, actionHandlers) => {
  // whether you want to use `echo` or the handler check is totally up to you
  return (state = initialState, action) => {
      const handler = ACTION_HANDLERS[action.type]
      return handler ? handler(state, action) : state
  }
}

const counter = createReducer(0, {
  [COUNTER_INCREMENT]: (state, action) => state + action.payload
})
```

Overall, I don't think there's much to be gained by changing it. Appreciate the thought, though.

**Comment by simonjoom** [comment]
I m going to swap to mobx.. I don t know about performance result but code will be simpler for sure than redux..
