### ISSUE TITLE
Image load not working in scss

### ISSUE THREAD

**Issue by mehdibalouchi** [davezuko/react-redux-starter-kit#935]
I am using starter kit recently and I have a problem with loading images in scss file.
I want to use background-image attribute for a div and loader does not load the image file.

I have this code in my scss file:
background-image: url('./assets/Pattern.png');

there is a directory named assets near the scss file containing above line of code.
when bundle restarts I get this error:

ERROR in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./src/components/AtGlanceSection/AtGlanceSection.scss
Module not found: Error: Cannot resolve module 'assets/Pattern.svg' in /home/mehdi/Git/Hamijoo/src/components/AtGlanceSection
 @ ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./src/components/AtGlanceSection/AtGlanceSection.scss 6:344-373

I've checked a few solutions changing webpack config and got nothing.
what should I do?

Thanks for your response.

**Comment by BorelTung** [comment]
Meet the same problem, any solutions?

**Comment by mehdibalouchi** [comment]
It has been 6 days now. any solution????

**Comment by nmrony** [comment]
@BorelTung @mehdibalouchi create assets directory in  components directory put your image files in there. Do not use relative path from rather use relative path from the `scss` file. Thus I resolve this for now. I think we should have this in README if this is the way to go. what do you think? @davezuko

**Comment by mehdibalouchi** [comment]
@nmrony I already have an assets directory near my scss file and I am using relative path from my stylesheet. But no matter where my image file exists and how relatively I am addressing the file, it doesn't load the image.

**Comment by nmrony** [comment]
@mehdibalouchi Can you please add some sample code? Please check the snap
![sanp](https://cloud.githubusercontent.com/assets/2513341/17200610/b7d80d1e-54a8-11e6-872c-a4534a024a8a.png)

**Comment by alanrubin** [comment]
I'm experience the exactly same issue, it doesn't matter if I put the image on the same directory of the scss/css file or not. I always use absolute paths. It finds the asset (otherwise the error message would be different) but says it cannot resolve the module for the image - it seems to me css modules are unable to find the url/file loader for the image to understand how to process it. Any ideas ? 

This is a bit of annoying, my work around was to use React styles object to declare the image background so that I can import them in JS and not in CSS.

Here is the error message:

`ERROR in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/containers/AppContainer.css
Module not found: Error: Cannot resolve module 'my-image.png' in /Users/alanrubin/projects/kiosk/src/containers
 @ ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/containers/AppContainer.css 6:81-113`

**Comment by BorelTung** [comment]
I've fix this issue in my project. Maybe this would help. See [postcss-loader issue#83](https://github.com/postcss/postcss-loader/issues/83) .

**Comment by nmrony** [comment]
@BorelTung That's what I was referring to. That's nice workaround

**Comment by fingermark** [comment]
I have my image in ./src/static and am trying to access it with background: url('/image.png');  webpack is able to find it -- if I change the image name I get an error -- but it doesn't seem to load in Chrome.  Chrome doesn't show a network request for that image.

**Comment by drock512** [comment]
This is what worked for me.  Update the url in the scss file to be relative to the 'src' directory.  For example: 

// src/components/MySweetComponent/MySweetComponent.scss
background-image: url('./components/MySweetComponent/assets/bg.png');

**Comment by Blackening999** [comment]
OMG! That's really sucks :(
I still cannot use url in my file though issue seemed to be closed!

I'm using LESS with pure build like this:

```less
@bg-logo: url('/routes/Home/assets/loggo.png');
```

and it cannot load it. I also tried to use public folder which seems to be completely useless in that matter too.

Please help!
