### ISSUE TITLE
How to run the files after `npm run compile`

### ISSUE THREAD

**Issue by tonyalaribe** [davezuko/react-redux-starter-kit#94]
I just completed development on an app, and have compiled it into a static build. the build folder contains a client and server folder. I'm new to node, so I have no idea how to run this compiled version and probably push it to heroku. 
Please help. Thanks.

**Comment by davezuko** [comment]
If you want server-side rendering, you'll need to tell Heroku to run `npm run server:start` (or probably install [forever](https://github.com/foreverjs/forever) and use that to run the script). Check https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile for more on this.

If you aren't using the server and have no interest in server-side rendering, you should just be able to host the `~/dist/client` folder since that contains the base index.html file as well as the compiled assets. I haven't used Heroku in a very long time so I'm not quite sure whether or not this is possible with that platform. If you want a purely static site, you may want to try something like https://pages.github.com/ in which case you'd need to either fork it for deployment (so that you can deploy the assets to the project root) or [create a gh-pages branch](https://help.github.com/articles/creating-project-pages-manually/).

Hope that helps.

**Comment by tonyalaribe** [comment]
Thanks @davezuko. I kept running 'node index.js'.

**Comment by OKNoah** [comment]
@tonyalaribe What did you end up doing here?

**Comment by OKNoah** [comment]
@davezuko If I'm not mistaken, `npm run server:start` has been removed from the `package.json`. Is there a new recommended way of deploying and running on Heroku?
