### ISSUE TITLE
initialState set in main.js is overriden when createStore is called.

### ISSUE THREAD

**Issue by SahilDude89ss** [davezuko/react-redux-starter-kit#953]
#The following is set in index.html.
window.___INITIAL_STATE__ = {
    profile: { 
        name: "Sahil Sharma"
    }
};

In main.js the following is happening;
const initialState = window.___INITIAL_STATE__

But the following code totally overrides what was set in the initialState. Is there a workaround?

const store = createStore(initialState, browserHistory);
const history = syncHistoryWithStore(browserHistory, store, {
    selectLocationState: (state) => {
        return state.router;
    }
});

Thanks

**Comment by brianzinn** [comment]
I approached that a bit differently.  I did not use index.html, but stored another variable:
`window.__PROFILE__ = profile: { 
    name: "Sahil Sharma"
}};`
In main.js you can merge them:
`const initialState = {...window.__INITIAL_STATE__, profile: window.__PROFILE__}`

The code you are showing here does not overwrite the initial state for me.  That does set the start state for the Store.  In this case it would set the profile.  I think it may because you are setting it in the index.html.  Try a breakpoint to find the timing, if you do "node run dev" look in webpack sources.  Cheers.

**Comment by SahilDude89ss** [comment]
Hi @brianzinn 

Thanks for the reply. I tried the above but there is no difference. 
So apparently the problem lies in the createStore function imported from redux library. It just drops the initialState. Not sure why it does that.

Thanks

**Comment by SahilDude89ss** [comment]
I figured out why the initial state values were being dropped. They were being dropped in createStore function as we did not have any co-relating reducers for them at that stage. Injecting the reducers with the initial state fixes the issue.

I think it would be nice to mention that in the file.
